/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtensionListProductPanel.java
 *
 * Created on Feb 3, 2012, 8:06:42 AM
 */
package vn.com.hkt.pilot.sb41.product.extW48.ui.panel;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import org.openide.util.Lookup;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.sb41.Installer;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class ExtensionListProductPanel extends javax.swing.JPanel implements IUserInterface {

    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();

    /** Creates new form ExtensionListProductPanel */
    public ExtensionListProductPanel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        tableListExtProduct.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableListExtProduct, colorL, null, colorD, null);
    }

    public JTable getTableListExtProduct() {
        return tableListExtProduct;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListExtProduct = new javax.swing.JTable();

        tableListExtProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null}
            },
            new String [] {
                "Mã", "Logo", "Tên sản phẩm", "Nhà cung cấp","Quốc kỳ nước sx","Nước sản xuất","Thành phố","Ngày sản xuất","Ngày sửa",
                "Hạn sử dụng","Tình trạng"
            }
        ));
        jScrollPane1.setViewportView(tableListExtProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListExtProduct;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách thông tin chi tiết sản xuất của sản phẩm";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
