/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListSB11.java
 *
 * Created on Feb 15, 2012, 10:10:19 AM
 */
package vn.com.hkt.pilot.subenterprise.ui.panel;

import com.vn.hkt.core.cookie.api.FilterCokieTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.japura.gui.LinkLabel;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import vn.com.hkt.basic.api.IEnterpriseBN;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.basic.api.IWidthTableBN;
import vn.com.hkt.basic.toolbar.BasicToolbarManager;
import vn.com.hkt.pilot.enterprise.viewer.api.EditCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnableButton;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnterpriseCreator;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnterpriseExtCreator;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnterpriseExtViewer;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnterpriseViewer;
import vn.com.hkt.pilot.enterprise.viewer.api.IGetObject;
import vn.com.hkt.pilot.enterprise.viewer.api.RemoveCookie;
import vn.com.hkt.pilot.enterprise.viewer.api.ResetCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.SaveCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.ViewCookieList;
import vn.com.hkt.pilot.entities.Enterprise;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.report.api.IReportListGUI;
import vn.com.hkt.pilot.report.api.IReportManager;
import vn.com.hkt.pilot.sbenterprise.Installer;
import vn.com.hkt.pilot.sbenterprise.entity.SubEnterprise;
import vn.com.hkt.pilot.subenterprise.dao.SubEnterpriseBN;
import vn.com.hkt.pilot.toobar.api.IResetFontSize;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
@ServiceProvider(service = IEnterpriseExtViewer.class)
public class ListSB11 extends javax.swing.JPanel implements IEnterpriseExtViewer, MouseMotionListener,
        RemoveCookie, ViewCookieList, ResetCookieList, FilterCokieTable, EditCookieList, SaveCookieList,
        IResetFontSize, IUserInterface, IReportListGUI {

    private SubEnterpriseBN subEnterpriseBN = new SubEnterpriseBN();
    private boolean isEdit = false;
    private int itsRow = 0;
    private int itsColumn = 0;
    private int size;
    private String font;
    private ISystemSotfwareBN sotfwareBN ;
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();
    private TableRowSorter<TableModel> tableRowSorter;

    /**
     * Creates new form ListSB11
     */
    public ListSB11() {
        initComponents();

        sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
        table.addMouseMotionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Logo", "Tên thường gọi", "Loại hình", "Ngày thành lập", "Ngày đăng ký", "Lần đăng ký", "Số đăng ký KD", "Mã số thuế", "Tình trạng"
            }
        ));
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title0")); // NOI18N
        table.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title1")); // NOI18N
        table.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title2")); // NOI18N
        table.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title3")); // NOI18N
        table.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title4")); // NOI18N
        table.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title5")); // NOI18N
        table.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title6")); // NOI18N
        table.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title7")); // NOI18N
        table.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title8")); // NOI18N
        table.getColumnModel().getColumn(9).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB11.class, "ListSB11.table.columnModel.title9")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getEnterpriseExtViewer() {
        return this;
    }

    @Override
    public Lookup getEnterpriseExtLookup() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public Lookup getEnterpriseLookup() {
        return null;
    }

    @Override
    public String toString() {
        return "Thông tin pháp nhân";
    }

    @Override
    public double getLevelNumber() {
        return 1.1;
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        JTable aTable = (JTable) e.getSource();
        itsRow = aTable.rowAtPoint(e.getPoint());
        itsColumn = aTable.columnAtPoint(e.getPoint());
        aTable.repaint();
    }

    @Override
    public void remove() throws IOException {
        int row = table.getSelectedRow();
        if (row >= 0) {
            Enterprise bean = (Enterprise) table.getValueAt(row, 2);
            Collection<? extends RemoveCookie> allRemoveCookie = Lookup.getDefault().lookupAll(RemoveCookie.class);
            for (RemoveCookie r : allRemoveCookie) {
                if (r instanceof IEnterpriseExtViewer || r instanceof IEnterpriseViewer) {
                    r.removeObject(bean.getId());
                }
            }
        }
    }

    @Override
    public void removeObject(int id) throws IOException {
        List<SubEnterprise> list = subEnterpriseBN.select(SubEnterprise.FIELD_ENTERPRISE_ID_ACTUAL, String.valueOf(id));
        SubEnterprise bean = list.get(0);
        subEnterpriseBN.delete(bean.getId());

    }

    @Override
    public void ViewCookieList() throws IOException {
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    protected void setupTable() {
        IWidthTableBN widthTableBN = Lookup.getDefault().lookup(IWidthTableBN.class);
        table.setSelectionBackground(new Color(192, 210, 224));
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        StripedTableCellRenderer.installInColumn(table, colorL, null, colorD, null);
        int sizeId = widthTableBN.getWidth1();
        int sizeLogo = widthTableBN.getWidth2();
        int sizeName = widthTableBN.getWidth3();


        table.getColumnModel().getColumn(0).setMaxWidth(sizeId);
        table.getColumnModel().getColumn(0).setPreferredWidth(sizeId);

        table.getColumnModel().getColumn(1).setMaxWidth(sizeLogo);
        table.getColumnModel().getColumn(1).setPreferredWidth(sizeLogo);

        table.getColumnModel().getColumn(2).setMaxWidth(sizeName);
        table.getColumnModel().getColumn(2).setPreferredWidth(sizeName);

        for (int i=0;i<=9;i++){
            table.getColumnModel().getColumn(i).setResizable(false);
        }

        table.getTableHeader().setReorderingAllowed(false);
        table.setRowHeight(26);
    }

    @Override
    public void EditCookieList(boolean b) throws IOException {
        isEdit = b;
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    @Override
    public void SaveCookieList() throws IOException {
        SubEnterpriseBN dao = new SubEnterpriseBN();
        IEnterpriseBN enterpriseBN = Lookup.getDefault().lookup(IEnterpriseBN.class);
        TopComponent tc = WindowManager.getDefault().findTopComponent("EnterpriseViewerTopComponent");
        if (tc.isShowing()) {
            int n = table.getRowCount();
            if (n <= 0) {
                return;
            }

            for (int i = 0; i < n; i++) {
                String id = table.getValueAt(i, 0).toString();

                String type = table.getValueAt(i, 3).toString().trim();

                Calendar c1 = Calendar.getInstance();
                Calendar c2 = Calendar.getInstance();

                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date d1 = new Date();
                Date d2 = new Date();

                try {
                    String dateStart = table.getValueAt(i, 4).toString();
                    d1 = sdf.parse(dateStart);
                    c1.setTime(d1);
                } catch (Exception e) {
                    d1 = null;
                }

                try {
                    String dateRegister = table.getValueAt(i, 5).toString();
                    d2 = sdf.parse(dateRegister);
                    c2.setTime(d2);
                } catch (Exception e) {
                    d2 = null;
                }


                int register = Integer.parseInt(table.getValueAt(i, 6).toString().trim());
                int c = Integer.parseInt(table.getValueAt(i, 7).toString().trim());
                int idTax = Integer.parseInt(table.getValueAt(i, 8).toString().trim());
                String state = table.getValueAt(i, 9).toString();
                Enterprise e = enterpriseBN.getByObjectId(id);
                List<SubEnterprise> ext = subEnterpriseBN.select(SubEnterprise.FIELD_ENTERPRISE_ID_ACTUAL, String.valueOf(e.getId()));
                SubEnterprise bean = ext.get(0);
                bean.setEnterpriseIdActual(e.getId());
                bean.setBookRegisterBussines(c);
                bean.setDateRegister(c1);
                if (d1 != null) {
                    bean.setDateStart(c1);
                } else {
                    bean.setDateStart(null);
                }
                if (d2 != null) {
                    bean.setDateRegister(c2);
                } else {
                    bean.setDateRegister(null);
                }
                bean.setIdTax(idTax);
                bean.setRegister(register);
                bean.setType(type);
                bean.setState(state);

                dao.update(bean);
            }


            loadDataEdit();
        }

    }

    private void loadData() {
        // model = this.getModel();
        this.table.removeAll();
        table.setModel(this.getModel());
        filterTable(table, getModel());
        resetTable();
        setupTable();
    }

    private void loadDataEdit() {
        // modelEdit = getModel();
        this.table.removeAll();
        table.setModel(this.getModel());
        resetTableEdit();
        setupTable();
    }

    public DefaultTableModel getModel() {
        IEnterpriseBN enterpriseBN = Lookup.getDefault().lookup(IEnterpriseBN.class);
        String[] header = {"Mã công ty", "Logo", "Tên thường gọi", "Loại hình", "Ngày thành lập", "Ngày đăng ký", "Lần đăng ký", "Số đăng ký KD", "Mã số thuế", "Tình trạng"};
        DefaultTableModel m = new DefaultTableModel(header, 0){
             boolean[] canEdit = new boolean[]{
                false, false, false, true, true, true, true, true, true, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        List<SubEnterprise> list = new ArrayList<SubEnterprise>();
        list = subEnterpriseBN.selectAll();
        for (SubEnterprise bean : list) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

            String dateStart = "";
            try {
                Calendar c1 = bean.getDateStart();
                dateStart = sdf.format(c1.getTime());
            } catch (Exception e) {
                dateStart = "";
            }

            String dateRegister = "";
            try {
                Calendar c2 = bean.getDateRegister();
                dateRegister = sdf.format(c2.getTime());
            } catch (Exception e) {
                dateRegister = "";
            }
            Enterprise e;
            try {
                e = enterpriseBN.getById(bean.getEnterpriseIdActual());
            } catch (Exception ex) {
                e = enterpriseBN.getById(1);
            }
            try {
                Object[] rows = {e.getEnterpriseId(), " Logo ", e, bean.getType(), dateStart, dateRegister, bean.getRegister(), bean.getBookRegisterBussines(), bean.getIdTax(), bean.getState()};
                m.addRow(rows);
            } catch (NullPointerException ex) {
            }

        }

        return m;
    }

    private void resetTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        TableCell tableCell = new TableCell(colorL, colorD);
        table.getColumnModel().getColumn(2).setCellRenderer(tableCell);
    }

    private void resetTableEdit() {
        ListSb11Cell listSb11Cell = new ListSb11Cell(table.getRowCount());
        table.getColumnModel().getColumn(3).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(4).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(5).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(6).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(7).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(8).setCellEditor(listSb11Cell);
        table.getColumnModel().getColumn(9).setCellEditor(listSb11Cell);
        //
    }

    // Liên thông font cỡ chữ, màu
    @Override
    public void resetFont() {
        listS = sotfwareBN.selectAll();
        size = table.getFont().getSize();
        font = listS.get(0).getFont().getFontName();
        table.setFont(new Font(font, 0, size));
    }

    @Override
    public void resetColorRowTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        StripedTableCellRenderer.installInColumn(table, colorL, null, colorD, null);
        table.repaint();
    }

    @Override
    public void resetSize() {
        listS = sotfwareBN.selectAll();
        font = table.getFont().getFontName();
        size = listS.get(0).getSizeWord();
        table.setFont(new Font(font, 0, size));
        for (int i = 0; i < table.getRowCount(); i++) {
            table.setRowHeight(i, size + 10);
        }
    }

    @Override
    public void resetColorWord() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        table.setForeground(color);
        table.repaint();
    }

    @Override
    public void resetColorTitle() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorTitle().getRed(), listS.get(0).getColorTitle().getGreen(), listS.get(0).getColorTitle().getBlue());
        table.getTableHeader().setForeground(color);
        table.repaint();
    }

    @Override
    public void resetColorMouse() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorMouseClick().getRed(), listS.get(0).getColorMouseClick().getGreen(), listS.get(0).getColorMouseClick().getBlue());
        table.setSelectionBackground(color);
        table.repaint();
    }

    @Override
    public void resetCookie() throws IOException {
        ViewCookieList();
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách thông tin kinh doanh của doanh nghiệp";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }

    @Override
    public void filterTable(JTable table, DefaultTableModel tableModel) {
        tableRowSorter = new TableRowSorter<TableModel>(tableModel);
        table.setRowSorter(tableRowSorter);
    }

    @Override
    public void filterTable(String stringKey, int column) {
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + stringKey, column));
        tableRowSorter.setSortKeys(null);
    }

    @Override
    public Hashtable<Integer, String> getTableHeader() {
        Hashtable<Integer, String> hashtable;
        hashtable = new Hashtable<Integer, String>();
        int n = table.getColumnCount();
        int i;
        for (i = 0; i < n; i++) {
            hashtable.put(i, table.getColumnName(i).toString());
        }
        return hashtable;
    }

    @Override
    public void exportReport() {
        IReportManager reportManager = Lookup.getDefault().lookup(IReportManager.class);

        if (reportManager
                == null) {
            return;
        }
        String[] keys1 = {"prTenDoanhNghiep", "prDiaChi", "prTenBaoCao", "prNgayLap", "prNguoiLapBaoCao"};
        String[] values1 = {"HKT Consultant", "66 Trần Thái Tông Hà Nội", "", "16/03/2012", "Đồng Thị Tâm"};
        String keys2[] = new String[table.getColumnCount()];
        String values2[] = new String[table.getColumnCount()];
        for (int i = 0; i < table.getColumnCount(); i++) {
            keys2[i] = "prColumn_" + i;
            values2[i] = table.getColumnName(i).toString();
        }
        String[] keys = new String[keys1.length + keys2.length];
        String[] values = new String[values1.length + values2.length];
        System.arraycopy(keys1, 0, keys, 0, keys1.length);
        System.arraycopy(keys2, 0, keys, keys1.length, keys2.length);
        System.arraycopy(values1, 0, values, 0, values1.length);
        System.arraycopy(values2, 0, values, values1.length, values2.length);
        HashMap map = reportManager.getHashMap(keys, values);
        DefaultTableModel md = reportManager.getModel(table);
        reportManager.setReportManager(map, md);
        reportManager.exportReport();
    }

    public class TableCell extends JLabel implements TableCellRenderer {

        private Color colorL;
        private Color colorD;

        public TableCell(Color colorL, Color colorD) {
            this.colorL = colorL;
            this.colorD = colorD;
            setOpaque(true);
        }
        private LinkLabel label = new LinkLabel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            table.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    mouseEvent(evt);
                }
            });
            if (row == itsRow && column == itsColumn) {

                if (itsColumn == 2) {
                    if (table.getValueAt(itsRow, 2) != null) {
                        label.setText(table.getValueAt(itsRow, 2).toString());
                    } else {
                        label.setText(" ");
                    }
                }


                return label;
            } else {
                if (value != null) {
                    this.setText(value.toString());
                } else {
                    this.setText(" ");
                }
                if (row == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row == 1) {
                    this.setBackground(colorD);
                    return this;
                }
                if (row % 2 == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row % 2 != 0) {
                    this.setBackground(colorD);
                    return this;
                }
                return this;
            }
            //
        }
        // Xử lý click đúp lấy dữ liệu từ list sang form nhap

        public void mouseEvent(MouseEvent e) {
            if (isEdit == true) {
                return;
            }
            JTable aTable = (JTable) e.getSource();
            int selct = aTable.getSelectedRow();
            int sectcol = aTable.getSelectedColumn();


            if (selct == itsRow && sectcol == 2) {
                if (aTable.getValueAt(selct, sectcol) != null) {
                    Enterprise p1 = (Enterprise) aTable.getValueAt(selct, sectcol);
                    TopComponent tc1 = WindowManager.getDefault().findTopComponent("EnterpriseViewerTopComponent");
                    if (tc1.isOpened()) {
                        tc1.close();
                    }
                    TopComponent tc = WindowManager.getDefault().findTopComponent("EnterpriseCreatorTopComponent");
                    if (tc.isOpened() == false) {
                        tc.open();
                        tc.requestActive();
                    } else {
                        tc.requestActive();
                    }
                    if (tc instanceof IEnableButton) {
                        try {
                            ((IEnableButton) tc).enableButton();
                        } catch (IOException ex) {
                            Exceptions.printStackTrace(ex);
                        }
                    }
                    toolbarEnterprise(p1);
                    getEnterprise(p1.getEnterpriseId());
                }

            }
            aTable.clearSelection();
        }

        private void toolbarEnterprise(Enterprise p1) {
            BasicToolbarManager.getBasicToolbar().loadEnterprise();
            BasicToolbarManager.getBasicToolbar().setEnterprise(p1);
        }
    }

    @Override
    public JTable getTable() {
        return table;
    }

    // Lấy liên thông Enterprise
    private void getEnterprise(String id) {
        Collection<? extends IGetObject> allSave = Lookup.getDefault().lookupAll(IGetObject.class);
        for (IGetObject getObject : allSave) {
            if (getObject instanceof IEnterpriseCreator || getObject instanceof IEnterpriseExtCreator) {
                getObject.getObject(id);
            }
        }
    }
}
