/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PersonPanel.java
 *
 * Created on Nov 23, 2011, 3:16:47 PM
 */
package vn.com.hkt.hrm.person.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import vn.com.hkt.basic.Installer;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.entities.system.dao.SystemSotfwareDAO;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class PersonPanel extends javax.swing.JPanel implements IUserInterface {

    private byte[] dataImages;
    private static PersonPanel personPanel;
    private ImageIcon imageChoise;
    private PersonCell personCell = new PersonCell();
    private SystemSotfwareDAO sotfwareBN = new SystemSotfwareDAO();
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();

    public PersonCell getPersonCell() {
        return personCell;
    }

    public static PersonPanel getPersonPanel() {
        if (personPanel == null) {
            personPanel = new PersonPanel();
        }
        return personPanel;
    }

    public byte[] getDataImages() {
        return dataImages;
    }

    public JLabel getLabelImage() {
        return lbImage;
    }

    /** Creates new form PersonPanel */
    public PersonPanel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        tabelPerson.getColumnModel().getColumn(1).setCellEditor(personCell);
        tabelPerson.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelPerson.getColumnModel().getColumn(0).setMaxWidth(100);
        tabelPerson.setRowSelectionAllowed(true);
        tabelPerson.setColumnSelectionAllowed(false);
        tabelPerson.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tabelPerson, colorL, null, colorD, null);
        tabelPerson.setForeground(color);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setBorder(null);
        tabelPerson.setTableHeader(null);
        this.removeAll();
        this.setLayout(new BorderLayout());
        panelTable.removeAll();
        panelTable.setLayout(new GridLayout());
        panelTable.add(tabelPerson);
        panelTP.setLayout(new GridLayout());
        panelTP.add(panlePhoto);
        panelTP.add(panelTable);
        panlePhoto.setSize(new Dimension(WIDTH, 170));
        panelTable.setSize(new Dimension(WIDTH, 170));
        this.add(panelTong, BorderLayout.CENTER);
        JLabel label = new JLabel("       Thông tin cơ bản");
        label.setFont((new Font(" ", Font.BOLD, 14)));
        label.setForeground(new Color(0, 51, 102));
        label.setPreferredSize(new Dimension(WIDTH, 30));
        // label.setHorizontalAlignment(50);
        this.add(label, BorderLayout.NORTH);
        this.setAutoscrolls(true);
    }

    @Override
    public String toString() {
        return "Thông tin chính";
    }

    public JTable getTabelPerson() {
        return tabelPerson;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTong = new javax.swing.JPanel();
        panelTP = new javax.swing.JPanel();
        panlePhoto = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPerson = new javax.swing.JTable();

        panelTP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTP.setPreferredSize(new java.awt.Dimension(827, 164));

        panlePhoto.setPreferredSize(new java.awt.Dimension(298, 164));

        lbImage.setText(org.openide.util.NbBundle.getMessage(PersonPanel.class, "PersonPanel.lbImage.text")); // NOI18N
        lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panlePhotoLayout = new javax.swing.GroupLayout(panlePhoto);
        panlePhoto.setLayout(panlePhotoLayout);
        panlePhotoLayout.setHorizontalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panlePhotoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        panlePhotoLayout.setVerticalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlePhotoLayout.createSequentialGroup()
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelTable.setPreferredSize(new java.awt.Dimension(412, 164));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 164));

        tabelPerson.setBackground(new java.awt.Color(242, 241, 240));
        tabelPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{
                {"Họ Tên", " "},
                {"Mã Person", " "},
                {"Quốc tịch", " "},
                {"Công ty", " "},
                {"Bộ phận", " "},
                {"Chức vụ", " "}

            },
            new String[]{
                "", ""
            }) {

                boolean[] canEdit = new boolean[]{
                    false, true
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            tabelPerson.setRowHeight(26);
            tabelPerson.setShowHorizontalLines(false);
            tabelPerson.setShowVerticalLines(false);
            jScrollPane1.setViewportView(tabelPerson);

            javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
            panelTable.setLayout(panelTableLayout);
            panelTableLayout.setHorizontalGroup(
                panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            );
            panelTableLayout.setVerticalGroup(
                panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout panelTPLayout = new javax.swing.GroupLayout(panelTP);
            panelTP.setLayout(panelTPLayout);
            panelTPLayout.setHorizontalGroup(
                panelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTPLayout.createSequentialGroup()
                    .addComponent(panlePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
            );
            panelTPLayout.setVerticalGroup(
                panelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addComponent(panlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout panelTongLayout = new javax.swing.GroupLayout(panelTong);
            panelTong.setLayout(panelTongLayout);
            panelTongLayout.setHorizontalGroup(
                panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTP, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
            );
            panelTongLayout.setVerticalGroup(
                panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTongLayout.createSequentialGroup()
                    .addComponent(panelTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(325, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
        }// </editor-fold>//GEN-END:initComponents

    private void lbImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImageMouseClicked
        if (evt.getClickCount() < 2 || !tabelPerson.isEnabled()) {
            return;
        }
        FileDialog fd = new FileDialog(new JDialog(), "Chọn ảnh");
        fd.setVisible(true);
        String d = fd.getDirectory();
        String f = fd.getFile();
        if (d == null || f == null) {
            return;
        }
        String fileName = d + f;
        try {
            ImageIcon image = new ImageIcon(fileName);
            Image img = image.getImage();
            Image newimg = img.getScaledInstance(lbImage.getWidth(), lbImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
            imageChoise = new ImageIcon(newimg);            
        } catch (Exception e) {
            imageChoise = new ImageIcon();
        }
        loadImage();
	 }//GEN-LAST:event_lbImageMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JPanel panelTP;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTong;
    private javax.swing.JPanel panlePhoto;
    private javax.swing.JTable tabelPerson;
    // End of variables declaration//GEN-END:variables

    private byte[] convertImage2Byte(Image image) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            int width = image.getWidth(null);
            int height = image.getHeight(null);
            BufferedImage bi = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = bi.createGraphics();
            g2d.drawImage(image, 0, 0, null);
            ImageIO.write(bi, "JPEG", baos);
        } catch (IOException ex) {
            //handle it here.... not implemented yet...
        }
        return baos.toByteArray();
    }

    private void loadImage() {
        dataImages = convertImage2Byte(imageChoise.getImage());
        showImage();
    }
    private Icon icon;

    public void showImage() {
        try {
            if (dataImages == null) {
                lbImage.setText("Anh");
                lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                icon = new ImageIcon();
                lbImage.setIcon(icon);
            } else {
                lbImage.setEnabled(true);
                lbImage.setText("");
                lbImage.setBorder(null);
                icon = new ImageIcon(dataImages);
                lbImage.setIcon(imageChoise);
            }
        } catch (Exception e) {
            lbImage.setText("Anh");
            lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lbImage.setIcon(icon);
        }
    }

    public void setDataImages(byte[] dataImages) {
        this.dataImages = dataImages;
        if (dataImages != null) {
            this.imageChoise = new ImageIcon(dataImages);
        } else {
            this.imageChoise = new ImageIcon();
        }
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện thông tin cá nhân";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}