/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.pilot.promotion.ui.window;

import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.promotion.Installer;
import vn.com.hkt.pilot.promotion.viewer.api.IPromotionViewer;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.pilot.promotion.ui.window//PromotionViewer//EN",
autostore = false)
@TopComponent.Description(preferredID = "PromotionViewerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.pilot.promotion.ui.window.PromotionViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_PromotionViewerAction",
preferredID = "PromotionViewerTopComponent")
public final class PromotionViewerTopComponent extends TopComponent implements IUserInterface{

    private Collection<? extends IPromotionViewer> promotionViewers;
    private DefaultComboBoxModel comboBoxModel;
    private int index = 0;

    public PromotionViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(PromotionViewerTopComponent.class, "CTL_PromotionViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(PromotionViewerTopComponent.class, "HINT_PromotionViewerTopComponent"));

        //fillData();

    }

    public void fillData() {
        promotionViewers = Lookup.getDefault().lookupAll(IPromotionViewer.class);
        if (!promotionViewers.isEmpty()) {
            comboBoxModel = new DefaultComboBoxModel();
            for (IPromotionViewer iPromotionViewer : promotionViewers) {
                comboBoxModel.addElement(iPromotionViewer);
            }
            comboBoxModel.addElement(" ");
            cboOptionView.setModel(comboBoxModel);
            cboOptionView.addItemListener(new ItemListener() {

                @Override
                public void itemStateChanged(ItemEvent e) {
                    index = cboOptionView.getSelectedIndex();
                    loadData();
                    cboOptionView.setSelectedIndex(index);
                }
            });
        }
    }

    public void loadData() {
        cboOptionView.setModel(comboBoxModel);
        Object o = cboOptionView.getSelectedItem();
        if (o instanceof IPromotionViewer) {
            IPromotionViewer promotionViewer = (IPromotionViewer) o;
            JPanel panel = promotionViewer.getPromotionViewer();
            panelContent.setLayout(new GridLayout());
            panelContent.removeAll();
            invalidate();
            panelContent.add(panel);
            validate();
            repaint();
        } else {
            panelContent.setLayout(new GridLayout());
            panelContent.removeAll();
            invalidate();
            validate();
            repaint();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelView = new javax.swing.JPanel();
        cboOptionView = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        cboOptionView.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PromotionViewerTopComponent.class, "PromotionViewerTopComponent.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboOptionView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboOptionView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelContent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(PromotionViewerTopComponent.class, "PromotionViewerTopComponent.panelContent.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboOptionView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelView;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        fillData();
        //loadData();
    }

    @Override
    public void componentClosed() {
        panelContent.removeAll();
        panelContent.invalidate();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

     @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện chính xem danh sách giảm giá";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
