/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplementaryProductViewerPanel.java
 *
 * Created on Feb 24, 2012, 4:32:38 PM
 */
package vn.com.hkt.pilot.sb42.pricesheet.ui.panel;

import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.sb42.pricesheet.Installer;

/**
 *
 * @author khangpn
 */
public class SupplementaryProductViewerPanel extends javax.swing.JPanel implements IUserInterface {

    /** Creates new form SupplementaryProductViewerPanel */
    public SupplementaryProductViewerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplementaryProduct = new javax.swing.JTable();

        tblSupplementaryProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên SP"
            }
        ));
        jScrollPane1.setViewportView(tblSupplementaryProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplementaryProduct;
    // End of variables declaration//GEN-END:variables
     @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách sản phẩm bổ trợ cho khuyến mại";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
