/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListSB32Panel.java
 *
 * Created on Feb 15, 2012, 11:06:04 AM
 */
package vn.com.hkt.pilot.sb32.ui.panel;

import com.vn.hkt.core.cookie.api.FilterCokieTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.japura.gui.LinkLabel;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import vn.com.hkt.basic.api.IDepartmentBN;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.basic.api.IWidthTableBN;
import vn.com.hkt.basic.toolbar.BasicToolbarManager;
import vn.com.hkt.pilot.department.viewer.api.IDepartmentCreater;
import vn.com.hkt.pilot.department.viewer.api.IDepartmentExtCreater;
import vn.com.hkt.pilot.department.viewer.api.IDepartmentExtViewer;
import vn.com.hkt.pilot.enterprise.viewer.api.EditCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnableButton;
import vn.com.hkt.pilot.enterprise.viewer.api.IGetObject;
import vn.com.hkt.pilot.enterprise.viewer.api.RemoveCookieDepartment;
import vn.com.hkt.pilot.enterprise.viewer.api.ResetCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.SaveCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.ViewCookieList;
import vn.com.hkt.pilot.entities.Department;
import vn.com.hkt.pilot.entities.Enterprise;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.report.api.IReportListGUI;
import vn.com.hkt.pilot.report.api.IReportManager;
import vn.com.hkt.pilot.sb32.Installer;
import vn.com.hkt.pilot.sb32.deparment.extW43.entity.DepartmentExt_W43;
import vn.com.hkt.pilot.sb32.deparment.extW43.entity.Information;
import vn.com.hkt.pilot.sb32.department.extW43.dao.DepartmentExtW43_DAO;
import vn.com.hkt.pilot.sb32.department.extW43.dao.InformationBN;
import vn.com.hkt.pilot.toobar.api.IResetFontSize;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
@ServiceProvider(service = IDepartmentExtViewer.class)
public class ListSB32Panel extends javax.swing.JPanel implements IDepartmentExtViewer, MouseMotionListener, ViewCookieList, RemoveCookieDepartment, ResetCookieList,
        FilterCokieTable, EditCookieList, SaveCookieList, IResetFontSize, IUserInterface, IReportListGUI {

    private DefaultTableModel model, modelEdit;
    private DepartmentExtW43_DAO dao = new DepartmentExtW43_DAO();
    private int itsRow = 0;
    private int itsColumn = 0;
    private boolean isEdit = false;
    private int size;
    private String font;
    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();
    private TableRowSorter<TableModel> tableRowSorter;

    /**
     * Creates new form ListSB32Panel
     */
    public ListSB32Panel() {
        initComponents();
        tableSB32.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableSB32, new Color(220, 228, 231), null, new Color(235, 239, 242), null);

        tableSB32.addMouseMotionListener(this);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSB32 = new javax.swing.JTable();

        tableSB32.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Logo", "Tên dự án", "Tổng thu về", "Tổng chi", "Lợi nhuân(Lỗ)", "Tỉ suất lợi nhuận", "Đánh giá dự án", "Xếp hạng"
            }
        ));
        jScrollPane1.setViewportView(tableSB32);
        tableSB32.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title0")); // NOI18N
        tableSB32.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title1")); // NOI18N
        tableSB32.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title2")); // NOI18N
        tableSB32.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title3")); // NOI18N
        tableSB32.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title4")); // NOI18N
        tableSB32.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title5")); // NOI18N
        tableSB32.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title6")); // NOI18N
        tableSB32.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title7")); // NOI18N
        tableSB32.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB32Panel.class, "ListSB32Panel.tableSB32.columnModel.title8")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSB32;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getDepartmentExtViewer() {
        return this;
    }

    @Override
    public String toString() {
        return "Thông tin phân tích";
    }

    @Override
    public Lookup getDepartmentExtViewerLookup() {
        return null;
    }

    @Override
    public double getLevelNumber() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        if (isEdit == false) {
            JTable aTable = (JTable) e.getSource();
            itsRow = aTable.rowAtPoint(e.getPoint());
            itsColumn = aTable.columnAtPoint(e.getPoint());
            aTable.repaint();
        }
    }

    @Override
    public void ViewCookieList() throws IOException {
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    @Override
    public void remove() throws IOException {
        int row = tableSB32.getSelectedRow();
        if (row > 0) {
            Department bean = (Department) tableSB32.getValueAt(row, 2);
            Collection<? extends RemoveCookieDepartment> allRemoveCookie = Lookup.getDefault().lookupAll(RemoveCookieDepartment.class);
            for (RemoveCookieDepartment r : allRemoveCookie) {
                r.removeObject(bean.getId());
            }
        }
    }

    @Override
    public void removeObject(int i) throws IOException {
        InformationBN informationBN = new InformationBN();
        try {
            List<DepartmentExt_W43> list = dao.select(DepartmentExt_W43.FILED_DEPARTMENT_ID, String.valueOf(i));
            DepartmentExt_W43 bean = list.get(0);
            dao.delete(bean.getId());
            Information info = informationBN.getByObjectId(String.valueOf(i));
            informationBN.delete(info.getId());
        } catch (Exception e) {
        }
    }

    @Override
    public void resetCookie() throws IOException {
        ViewCookieList();
    }

    @Override
    public void EditCookieList(boolean b) throws IOException {
        isEdit = b;
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    @Override
    public void SaveCookieList() throws IOException {
    }

    public void resetTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        TableCell tableCell = new TableCell(colorL, colorD);
        tableSB32.getColumnModel().getColumn(2).setCellRenderer(tableCell);
        tableSB32.getColumnModel().getColumn(2).setPreferredWidth(200);
        tableSB32.setRowHeight(25);
    }

    public void resetTableEdit() {
        // Add ComboBox neu co
    }

    private void setupTable() {
        IWidthTableBN widthTableBN = Lookup.getDefault().lookup(IWidthTableBN.class);
        tableSB32.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableSB32, new Color(220, 228, 231), null, new Color(235, 239, 242), null);

        int sizeId = widthTableBN.getWidth1();
        int sizeLogo = widthTableBN.getWidth2();
        int sizeName = widthTableBN.getWidth3();


        tableSB32.getColumnModel().getColumn(0).setMaxWidth(sizeId);
        tableSB32.getColumnModel().getColumn(0).setPreferredWidth(sizeId);

        tableSB32.getColumnModel().getColumn(1).setMaxWidth(sizeLogo);
        tableSB32.getColumnModel().getColumn(1).setPreferredWidth(sizeLogo);

        tableSB32.getColumnModel().getColumn(2).setMaxWidth(sizeName);
        tableSB32.getColumnModel().getColumn(2).setPreferredWidth(sizeName);

        tableSB32.getColumnModel().getColumn(0).setResizable(false);
        tableSB32.getColumnModel().getColumn(1).setResizable(false);
        tableSB32.getColumnModel().getColumn(2).setResizable(false);
        tableSB32.getColumnModel().getColumn(3).setResizable(false);
        tableSB32.getColumnModel().getColumn(4).setResizable(false);
        tableSB32.getColumnModel().getColumn(5).setResizable(false);
        tableSB32.getTableHeader().setReorderingAllowed(false);
    }

    public DefaultTableModel getModel() {
        IDepartmentBN departmentBN = Lookup.getDefault().lookup(IDepartmentBN.class);
        Enterprise enterpriseChoise = null;
        DefaultTableModel m = new DefaultTableModel();
        String[] header = {"Mã", "Logo", "Tên dự án", "Tổng thu về", "Tổng chi", "Lợi nhuân(Lỗ)", "Tỉ suất lợi nhuận", "Đánh giá dự án", "Xếp hạng"};
        m = new DefaultTableModel(header, 0);
        enterpriseChoise = BasicToolbarManager.getBasicToolbar().getEnterprise();

        List<DepartmentExt_W43> list = new ArrayList<DepartmentExt_W43>();
        if (enterpriseChoise == null) {
            list = dao.selectAll();
        } else {
            list = dao.getByEnterpriser(enterpriseChoise);
        }

        int n = list.size();

        int i;
        for (i = 0; i < n; i++) {
            DepartmentExt_W43 d = list.get(i);
            if (d.getDepartmentIdActual() != -1) {
                Department department = departmentBN.getById(d.getDepartmentIdActual());
                Object[] row = {department.getDepartmentId(), "Logo", department, d.getSumMoneyImport(), d.getSumMoneyExport(), d.getSumprofit(), d.getProportionProfit(), d.getEstimate(), "Tính Sau"};
                m.addRow(row);
            }

        }
        return m;
    }

    protected void loadData() {
        model = getModel();
        tableSB32.removeAll();
        tableSB32.setModel(model);
        resetTable();
        setupTable();
        filterTable(getTable(), model);
    }

    public void loadDataEdit() {
        modelEdit = getModel();
        tableSB32.removeAll();
        tableSB32.setModel(modelEdit);
        resetTableEdit();
        setupTable();
    }

    // Liên thông font cỡ chữ, màu
    @Override
    public void resetFont() {
        listS = sotfwareBN.selectAll();
        size = tableSB32.getFont().getSize();
        font = listS.get(0).getFont().getFontName();
        tableSB32.setFont(new Font(font, 0, size));
    }

    @Override
    public void resetColorRowTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        StripedTableCellRenderer.installInColumn(tableSB32, colorL, null, colorD, null);
        tableSB32.repaint();
    }

    @Override
    public void resetSize() {
        listS = sotfwareBN.selectAll();
        font = tableSB32.getFont().getFontName();
        size = listS.get(0).getSizeWord();
        tableSB32.setFont(new Font(font, 0, size));

    }

    @Override
    public void resetColorWord() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        tableSB32.setForeground(color);
        tableSB32.repaint();
    }

    @Override
    public void resetColorTitle() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorTitle().getRed(), listS.get(0).getColorTitle().getGreen(), listS.get(0).getColorTitle().getBlue());
        tableSB32.getTableHeader().setForeground(color);
        tableSB32.repaint();
    }

    @Override
    public void resetColorMouse() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorMouseClick().getRed(), listS.get(0).getColorMouseClick().getGreen(), listS.get(0).getColorMouseClick().getBlue());
        tableSB32.setSelectionBackground(color);
        tableSB32.repaint();
    }

    @Override
    public JTable getTable() {
        return tableSB32;
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách thông tin tài chính dự án";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }

    @Override
    public void filterTable(JTable table, DefaultTableModel tableModel) {
        tableRowSorter = new TableRowSorter<TableModel>(tableModel);
        table.setRowSorter(tableRowSorter);
    }

    @Override
    public void filterTable(String stringKey, int column) {
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + stringKey, column));
        tableRowSorter.setSortKeys(null);
    }

    @Override
    public Hashtable getTableHeader() {
        Hashtable hashtable = new Hashtable();
        int n = getTable().getColumnCount();
        int i;
        for (i = 0; i < n; i++) {
            hashtable.put(i, getTable().getColumnName(i).toString());
        }

        return hashtable;
    }

    @Override
    public void exportReport() {
        IReportManager reportManager = Lookup.getDefault().lookup(IReportManager.class);

        if (reportManager
                == null) {
            return;
        }
        String[] keys1 = {"prTenDoanhNghiep", "prDiaChi", "prTenBaoCao", "prNgayLap", "prNguoiLapBaoCao"};
        String[] values1 = {"HKT Consultant", "66 Trần Thái Tông Hà Nội", "", "16/03/2012", "Đồng Thị Tâm"};
        String keys2[] = new String[getTable().getColumnCount()];
        String values2[] = new String[getTable().getColumnCount()];
        for (int i = 0; i < getTable().getColumnCount(); i++) {
            keys2[i] = "prColumn_" + i;
            values2[i] = getTable().getColumnName(i).toString();
        }
        String[] keys = new String[keys1.length + keys2.length];
        String[] values = new String[values1.length + values2.length];
        System.arraycopy(keys1, 0, keys, 0, keys1.length);
        System.arraycopy(keys2, 0, keys, keys1.length, keys2.length);
        System.arraycopy(values1, 0, values, 0, values1.length);
        System.arraycopy(values2, 0, values, values1.length, values2.length);
        HashMap map = reportManager.getHashMap(keys, values);
        DefaultTableModel md = reportManager.getModel(getTable());
        reportManager.setReportManager(map, md);
        reportManager.exportReport();
    }

    public class TableCell extends JLabel implements TableCellRenderer {

        private Color colorL;
        private Color colorD;

        public TableCell(Color colorL, Color colorD) {
            this.colorL = colorL;
            this.colorD = colorD;
            setOpaque(true);
        }
        private LinkLabel label = new LinkLabel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            table.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    mouseEvent(evt);
                }
            });
            if (row == itsRow && column == itsColumn) {
                if (itsColumn == 2) {
                    if (table.getValueAt(itsRow, 2) != null) {
                        label.setText(table.getValueAt(itsRow, 2).toString());
                    } else {
                        label.setText(" ");
                    }
                }

                return label;
            } else {
                if (value != null) {
                    this.setText(value.toString());
                } else {
                    this.setText(" ");
                }
                if (row == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row == 1) {
                    this.setBackground(colorD);
                    return this;
                }
                if (row % 2 == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row % 2 != 0) {
                    this.setBackground(colorD);
                    return this;
                }
                return this;
            }
            //
        }
        // Xử lý click đúp lấy dữ liệu từ list sang form nhap

        public void mouseEvent(MouseEvent e) {
            if (isEdit == true) {
                return;
            }
            JTable aTable = (JTable) e.getSource();
            int selct = aTable.getSelectedRow();
            int sectcol = aTable.getSelectedColumn();
            if (selct == itsRow && sectcol == 2) {
                if (aTable.getValueAt(selct, sectcol) != null) {
                    Department d1 = (Department) aTable.getValueAt(selct, sectcol);

                    TopComponent tc1 = WindowManager.getDefault().findTopComponent("DepartmentViewerTopComponent");
                    if (tc1.isOpened()) {
                        tc1.close();
                    }
                    TopComponent tc = WindowManager.getDefault().findTopComponent("DepartmentCreatorTopComponent");
                    if (tc.isOpened() == false) {
                        tc.open();
                        tc.requestActive();
                    } else {
                        tc.requestActive();
                    }
                    if (tc instanceof IEnableButton) {
                        try {
                            ((IEnableButton) tc).enableButton();
                        } catch (IOException ex) {
                            Exceptions.printStackTrace(ex);
                        }
                    }
                    getObject(d1.getDepartmentId());
                }

            }
            aTable.clearSelection();
        }
    }

    private void getObject(String id) {
        Collection<? extends IGetObject> allSave = Lookup.getDefault().lookupAll(IGetObject.class);
        for (IGetObject getObject : allSave) {
            if (getObject instanceof IDepartmentCreater || getObject instanceof IDepartmentExtCreater) {
                getObject.getObject(id);
            }
        }
    }
}
