/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterpriseEditIDPanel.java
 *
 * Created on Feb 8, 2012, 4:44:23 PM
 */
package vn.com.hkt.erm.department.ui;

import java.util.List;
import javax.swing.JPanel;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import vn.com.hkt.basic.Installer;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnterpriseHelp;
import vn.com.hkt.pilot.entities.PrefixManager;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.keymanager.api.PrefixManagerBN;

/**
 *
 * @author longnt
 */
@ServiceProvider(service = IEnterpriseHelp.class)
public class DepartmentEditIDPanel extends javax.swing.JPanel implements IEnterpriseHelp, IUserInterface {

    private List<PrefixManager> prefjxManager = null;
    private PrefixManager keyManager;
    private PrefixManagerBN prefixManagerBN = new PrefixManagerBN();
    private static DepartmentEditIDPanel editIDPanel;
    private boolean getBoolean = false;

    public static DepartmentEditIDPanel getEditIDPanel() {
        if (editIDPanel == null) {
            editIDPanel = new DepartmentEditIDPanel();
        }
        return editIDPanel;
    }

    public boolean isGetBoolean() {
        return getBoolean;
    }

    /** Creates new form EnterpriseEditIDPanel */
    public DepartmentEditIDPanel() {
        initComponents();
        prefjxManager = prefixManagerBN.getPrefixByEntityName("Department");
        if (prefjxManager.isEmpty()) {
            keyManager = new PrefixManager("Department", "PD");
            prefixManagerBN.insert(keyManager);
        } else {
            keyManager = prefjxManager.get(0);
        }
        txtEditKey.setText(keyManager.getLastPrefix());
    }

    public PrefixManager getKeyManager() {
        return keyManager;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        txtEditKey.setText(org.openide.util.NbBundle.getMessage(DepartmentEditIDPanel.class, "DepartmentEditIDPanel.txtEditKey.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DepartmentEditIDPanel.class, "DepartmentEditIDPanel.jLabel1.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(DepartmentEditIDPanel.class, "DepartmentEditIDPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(txtEditKey, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        keyManager.setLastPrefix(txtEditKey.getText());
        prefixManagerBN.update(keyManager);
        getBoolean = true;
        TopComponent tc = WindowManager.getDefault().findTopComponent("DepartmentCreatorTopComponent");
        tc.close();
        tc.open();
        getBoolean = false;
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEditKey;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getPanel1() {
        return DepartmentEditIDPanel.getEditIDPanel();
    }

    @Override
    public JPanel getPanel2() {
        //TODO chua lam
        return null;
    }

    @Override
    public double getLevelNumber() {
        return 3.1;
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện giúp đỡ đối với phòng ban";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
