/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListDepartmentPanel.java
 *
 * Created on Nov 23, 2011, 4:00:14 PM
 */
package vn.com.hkt.erm.department.ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import org.openide.util.Lookup;
import vn.com.hkt.basic.Installer;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class ListDepartmentPanel extends javax.swing.JPanel implements IUserInterface {

    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();

    /** Creates new form ListDepartmentPanel */
    public ListDepartmentPanel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        tableListD.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableListD, colorL, null, colorD, null);

    }

    @Override
    public String toString() {
        return "Thông tin cơ bản";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListD = new javax.swing.JTable();

        tableListD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null,null,null}
            },
            new String [] {
                "Mã dự án","Logo","Tên dự án", "Logo Công ty", "Tên công ty", "Phòng phụ thuộc", "Trưởng dự án", "Sản phẩm chính"
            }
        ));
        tableListD.getColumnModel().getColumn(2).setPreferredWidth(500);
        jScrollPane1.setViewportView(tableListD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListD;
    // End of variables declaration//GEN-END:variables

    public JTable getTableListD() {
        return tableListD;
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách phòng ban";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
