/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterprisePanel.java
 *
 * Created on Nov 23, 2011, 1:56:14 PM
 */
package vn.com.hkt.erm.enterprise.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class EnterprisePanel extends javax.swing.JPanel {

    private byte[] dataImages;

    @Override
    public String toString() {
        return "Enterprise Base";
    }
    /** Creates new form EnterprisePanel */
    private EnterpriseCell enterpriseCell;

    public EnterprisePanel() {
        initComponents();
        enterpriseCell = new EnterpriseCell();
        tabelEnterprise.getColumnModel().getColumn(1).setCellEditor(enterpriseCell);
        tabelEnterprise.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelEnterprise.getColumnModel().getColumn(0).setMaxWidth(100);
        tabelEnterprise.setRowSelectionAllowed(true);
        tabelEnterprise.setColumnSelectionAllowed(false);
        tabelEnterprise.setSelectionBackground(new Color(201, 224, 252));
        tabelEnterprise.setBorder(BorderFactory.createLineBorder(new Color(255,255,255)));
        tabelEnterprise.setTableHeader(null);
        jScrollPane1.setViewportBorder(null);
        StripedTableCellRenderer.installInColumn(tabelEnterprise, new Color(241, 246, 253), null, null, null);
        this.removeAll();
        this.setLayout(new GridLayout());
        this.add(panlePhoto);
        this.add(panelTable);

    }

    public EnterpriseCell getEnterpriseCell() {
        return enterpriseCell;
    }

    public void setDataImages(byte[] dataImages) {
        this.dataImages = dataImages;
    }

    public byte[] getDataImages() {
        return dataImages;
    }

    public JTable getTabelEnterprise() {
        return tabelEnterprise;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEnterprise = new javax.swing.JTable();
        panlePhoto = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelTable.setBackground(new java.awt.Color(255, 255, 255));
        panelTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tabelEnterprise.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tabelEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tên công ty", " "},
                {"Mã công ty", " "},
                {"Công ty mẹ", " "},
                {"Đại diện pháp luật", " "},
                {"Slogan", " "}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelEnterprise.setRowHeight(26);
        tabelEnterprise.setShowHorizontalLines(false);
        tabelEnterprise.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabelEnterprise);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        panlePhoto.setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setText(org.openide.util.NbBundle.getMessage(EnterprisePanel.class, "EnterprisePanel.lbImage.text")); // NOI18N
        lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panlePhotoLayout = new javax.swing.GroupLayout(panlePhoto);
        panlePhoto.setLayout(panlePhotoLayout);
        panlePhotoLayout.setHorizontalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panlePhotoLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        panlePhotoLayout.setVerticalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlePhotoLayout.createSequentialGroup()
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLbImage() {
        return lbImage;
    }

    private void lbImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImageMouseClicked

        if (evt.getClickCount() == 2) {             loadImage();         }     }//GEN-LAST:event_lbImageMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panlePhoto;
    private javax.swing.JTable tabelEnterprise;
    // End of variables declaration//GEN-END:variables

    private void loadImage() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lbImage.getSize().height, lbImage.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lbImage.getSize().width, lbImage.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImages = baos.toByteArray();
            showImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
    private Icon icon;

    public void showImage() {
        if (dataImages == null) {
            return;
        }
        lbImage.setText("");
        lbImage.setBorder(null);
        icon = new ImageIcon(dataImages);
        lbImage.setIcon(icon);
        lbImage.setVisible(true);
    }
}
