/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtensionListDepartmentPanel.java
 *
 * Created on Feb 2, 2012, 8:50:43 AM
 */
package vn.com.hkt.pilot.sb31.ui.panel.ext_d_w41;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import org.openide.util.Lookup;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.sb31.Installer;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class ExtensionListDepartmentPanel extends javax.swing.JPanel implements IUserInterface {

    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();

    /** Creates new form ExtensionListDepartmentPanel */
    public ExtensionListDepartmentPanel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        tableExtDepartment.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableExtDepartment, colorL, null, colorD, null);
    }

    @Override
    public String toString() {
        return "Thông tin chi tiết";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableExtDepartment = new javax.swing.JTable();

        tableExtDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null},
                {null, null, null, null,null,null,null,null,null,null,null}
            },
            new String [] {
                "Mã dự án", "Logo", "Tên thường gọi",
                "Tình trạng", "Khách hàng", "Dự kiến triển khai", "Đã triển khai", "Ngày triển khai", "Dự kiến OK", "Đã ok","Ngày hoàn thành"}

        ));
        tableExtDepartment.getColumnModel().getColumn(2).setPreferredWidth(500);
        jScrollPane1.setViewportView(tableExtDepartment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTableExtDepartment() {
        return tableExtDepartment;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableExtDepartment;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách thông tin dự án";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
