/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListSB43Panel.java
 *
 * Created on Feb 15, 2012, 11:16:32 AM
 */
package vn.com.hkt.pilot.sb43.ui.panel;

import com.vn.hkt.core.cookie.api.FilterCokieTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.japura.gui.LinkLabel;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import vn.com.hkt.basic.api.IProductBN;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.basic.api.IWidthTableBN;
import vn.com.hkt.basic.toolbar.BasicToolbarManager;
import vn.com.hkt.pilot.enterprise.viewer.api.IGetObject;
import vn.com.hkt.pilot.enterprise.viewer.api.RemoveCookieProduct;
import vn.com.hkt.pilot.enterprise.viewer.api.ResetCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.ViewCookieList;
import vn.com.hkt.pilot.entities.Enterprise;
import vn.com.hkt.pilot.entities.Product;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.product.viewer.api.IProductCreater;
import vn.com.hkt.pilot.product.viewer.api.IProductExtCreater;
import vn.com.hkt.pilot.product.viewer.api.IProductExtViewer;
import vn.com.hkt.pilot.product.viewer.api.IProductViewer;
import vn.com.hkt.pilot.report.api.IReportListGUI;
import vn.com.hkt.pilot.report.api.IReportManager;
import vn.com.hkt.pilot.sb43.Installer;
import vn.com.hkt.pilot.sb43.entity.ProductExt_W52;
import vn.com.hkt.pilot.sb43.product.extW48.dao.ProductExt_W52BN;
import vn.com.hkt.pilot.toobar.api.IResetFontSize;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
@ServiceProvider(service = IProductExtViewer.class)
public class ListSB43Panel extends javax.swing.JPanel implements IProductExtViewer, MouseMotionListener, ViewCookieList, RemoveCookieProduct, ResetCookieList,
        LookupListener, FilterCokieTable, IResetFontSize, IUserInterface, IReportListGUI {

    /**
     * Creates new form ListSB43Panel
     */
    private ProductExt_W52BN dao = new ProductExt_W52BN();
    private int itsRow = 0;
    private int itsColumn = 0;
    private boolean isEdit = false;
    private int size;
    private String font;
    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();
    private TableRowSorter<TableModel> tableRowSorter;

    public ListSB43Panel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        tableSB43.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableSB43, colorL, null, colorD, null);
        tableSB43.addMouseMotionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSB43 = new javax.swing.JTable();

        tableSB43.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Ảnh", "Tên SPDV", "Tổng lượng xuất", "Tổng tiền xuất", "Tổng lượng nhập", "Tổng tiền nhập", "Lợi nhuận(Lỗ)", "Tỉ suất lợi nhuận", "Đánh giá", "Xếp hạng"
            }
        ));
        jScrollPane1.setViewportView(tableSB43);
        tableSB43.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title0")); // NOI18N
        tableSB43.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title1")); // NOI18N
        tableSB43.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title2")); // NOI18N
        tableSB43.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title3")); // NOI18N
        tableSB43.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title4")); // NOI18N
        tableSB43.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title5")); // NOI18N
        tableSB43.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title6")); // NOI18N
        tableSB43.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title7")); // NOI18N
        tableSB43.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title8")); // NOI18N
        tableSB43.getColumnModel().getColumn(9).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title9")); // NOI18N
        tableSB43.getColumnModel().getColumn(10).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB43Panel.class, "ListSB43Panel.tableSB43.columnModel.title10")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSB43;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getProductExtViewer() {
        return this;
    }

    @Override
    public String toString() {
        return "Thông tin phân tích";
    }

    @Override
    public Lookup getProductExtViewerLookup() {
        return null;
    }

    @Override
    public double getLevelNumber() {
        return -1;
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        JTable aTable = (JTable) e.getSource();
        itsRow = aTable.rowAtPoint(e.getPoint());
        itsColumn = aTable.columnAtPoint(e.getPoint());
        aTable.repaint();
    }

    @Override
    public void ViewCookieList() throws IOException {
        loadData();
    }

    @Override
    public void remove() throws IOException {
        int i = tableSB43.getSelectedRow(); // chọn hàng để xóa
        if (i >= 0) {
            Product bean = (Product) tableSB43.getValueAt(i, 2);
            Collection<? extends RemoveCookieProduct> allRemoveCookie = Lookup.getDefault().lookupAll(RemoveCookieProduct.class);
            for (RemoveCookieProduct r : allRemoveCookie) {
                if (r instanceof IProductExtViewer || r instanceof IProductViewer) {
                    r.removeObject(bean.getId());
                }
            }
            loadData();
        }
    }

    @Override
    public void removeObject(int id) throws IOException {
        List<ProductExt_W52> list = dao.select(ProductExt_W52.FILED_PRODUCT_ID_ACTUAL, String.valueOf(id));
        ProductExt_W52 bean = list.get(0);
        dao.delete(bean.getId());
    }

    @Override
    public void resetCookie() throws IOException {
        ViewCookieList();
    }

    @Override
    public void resultChanged(LookupEvent le) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    private void setupTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());

        IWidthTableBN widthTableBN = Lookup.getDefault().lookup(IWidthTableBN.class);
        tableSB43.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableSB43, colorL, null, colorD, null);

        int sizeId = widthTableBN.getWidth1();
        int sizeLogo = widthTableBN.getWidth2();
        int sizeName = widthTableBN.getWidth3();


        tableSB43.getColumnModel().getColumn(0).setMaxWidth(sizeId);
        tableSB43.getColumnModel().getColumn(0).setPreferredWidth(sizeId);

        tableSB43.getColumnModel().getColumn(1).setMaxWidth(sizeLogo);
        tableSB43.getColumnModel().getColumn(1).setPreferredWidth(sizeLogo);

        tableSB43.getColumnModel().getColumn(2).setMaxWidth(sizeName);
        tableSB43.getColumnModel().getColumn(2).setPreferredWidth(sizeName);

        tableSB43.getColumnModel().getColumn(0).setResizable(false);
        tableSB43.getColumnModel().getColumn(1).setResizable(false);
        tableSB43.getColumnModel().getColumn(2).setResizable(false);
        tableSB43.getColumnModel().getColumn(3).setResizable(false);
        tableSB43.getColumnModel().getColumn(4).setResizable(false);
        tableSB43.getColumnModel().getColumn(5).setResizable(false);
        tableSB43.getColumnModel().getColumn(6).setResizable(false);
        tableSB43.getColumnModel().getColumn(7).setResizable(false);
        tableSB43.getColumnModel().getColumn(8).setResizable(false);
        tableSB43.getColumnModel().getColumn(9).setResizable(false);
        tableSB43.getColumnModel().getColumn(10).setResizable(false);
        tableSB43.getTableHeader().setReorderingAllowed(false);
    }

    private void loadData() {
        DefaultTableModel model;
        Enterprise enterpriseChoise = null;
        IProductBN productBN = Lookup.getDefault().lookup(IProductBN.class);
        String[] header = {"Mã", "Ảnh", "Tên SPDV", "Tổng lượng xuất", "Tổng tiền xuất", "Tổng lượng nhập", "Tổng tiền nhập", "Lợi nhuận(Lỗ)", "Tỉ suất lợi nhuận", "Đánh giá", "Xếp hạng"};
        model = new DefaultTableModel(header, 0) {

            boolean[] canEdit = new boolean[]{
                false, false, false, true, true, true, true, true, true, true, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        enterpriseChoise = BasicToolbarManager.getBasicToolbar().getEnterprise();

        List<ProductExt_W52> list = new ArrayList<ProductExt_W52>();
        if (enterpriseChoise == null) {
            list = dao.selectAll();
        } else {
            list = dao.getByEnterpriser(enterpriseChoise);
        }


        int n = list.size();

        int i;
        for (i = 0; i < n; i++) {
            ProductExt_W52 p = list.get(i);
            if (p.getProductIdActual() != -1) {
                Product product = productBN.getById(p.getProductIdActual());
                Object[] row = {product.getProductId(), "Anh", product, p.getTotalNumberExport(), p.getTotalVauleExport(), p.getTotalNumberImport(), p.getTotalVauleImport(), p.getTotalProfit(),
                    p.getPercentProfit(), p.getDescription(), "Xep Hang"};
                model.addRow(row);
            }
        }
        tableSB43.removeAll();
        tableSB43.setModel(model);
        resetTable();
        setupTable();
        filterTable(getTable(), model);
    }

    public void resetTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        TableCell tableCell = new TableCell(colorL, colorD);
        tableSB43.getColumnModel().getColumn(2).setCellRenderer(tableCell);
        tableSB43.getColumnModel().getColumn(2).setPreferredWidth(200);
        tableSB43.setRowHeight(26);
    }

    // Liên thông font cỡ chữ, màu
    @Override
    public void resetFont() {
        listS = sotfwareBN.selectAll();
        size = tableSB43.getFont().getSize();
        font = listS.get(0).getFont().getFontName();
        tableSB43.setFont(new Font(font, 0, size));
    }

    @Override
    public void resetColorRowTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        StripedTableCellRenderer.installInColumn(tableSB43, colorL, null, colorD, null);
        tableSB43.repaint();
    }

    @Override
    public void resetSize() {
        listS = sotfwareBN.selectAll();
        font = tableSB43.getFont().getFontName();
        size = listS.get(0).getSizeWord();
        tableSB43.setFont(new Font(font, 0, size));

    }

    @Override
    public void resetColorWord() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        tableSB43.setForeground(color);
        tableSB43.repaint();
    }

    @Override
    public void resetColorTitle() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorTitle().getRed(), listS.get(0).getColorTitle().getGreen(), listS.get(0).getColorTitle().getBlue());
        tableSB43.getTableHeader().setForeground(color);
        tableSB43.repaint();
    }

    @Override
    public void resetColorMouse() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorMouseClick().getRed(), listS.get(0).getColorMouseClick().getGreen(), listS.get(0).getColorMouseClick().getBlue());
        tableSB43.setSelectionBackground(color);
        tableSB43.repaint();
    }

    @Override
    public JTable getTable() {
        return tableSB43;
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện danh sách thông tin nhập xuất sản phẩm";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }

    @Override
    public void filterTable(JTable table, DefaultTableModel tableModel) {
        tableRowSorter = new TableRowSorter<TableModel>(tableModel);
        table.setRowSorter(tableRowSorter);
    }

    @Override
    public void filterTable(String stringKey, int column) {
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + stringKey, column));
        tableRowSorter.setSortKeys(null);
    }

    @Override
    public Hashtable getTableHeader() {
        Hashtable hashtable = new Hashtable();
        int n = getTable().getColumnCount();
        int i;
        for (i = 0; i < n; i++) {
            hashtable.put(i, getTable().getColumnName(i).toString());
        }

        return hashtable;
    }

    @Override
    public void exportReport() {
        IReportManager reportManager = Lookup.getDefault().lookup(IReportManager.class);

        if (reportManager
                == null) {
            return;
        }
        String[] keys1 = {"prTenDoanhNghiep", "prDiaChi", "prTenBaoCao", "prNgayLap", "prNguoiLapBaoCao"};
        String[] values1 = {"HKT Consultant", "66 Trần Thái Tông Hà Nội", "", "16/03/2012", "Đồng Thị Tâm"};
        String keys2[] = new String[getTable().getColumnCount()];
        String values2[] = new String[getTable().getColumnCount()];
        for (int i = 0; i < getTable().getColumnCount(); i++) {
            keys2[i] = "prColumn_" + i;
            values2[i] = getTable().getColumnName(i).toString();
        }
        String[] keys = new String[keys1.length + keys2.length];
        String[] values = new String[values1.length + values2.length];
        System.arraycopy(keys1, 0, keys, 0, keys1.length);
        System.arraycopy(keys2, 0, keys, keys1.length, keys2.length);
        System.arraycopy(values1, 0, values, 0, values1.length);
        System.arraycopy(values2, 0, values, values1.length, values2.length);
        HashMap map = reportManager.getHashMap(keys, values);
        DefaultTableModel md = reportManager.getModel(getTable());
        reportManager.setReportManager(map, md);
        reportManager.exportReport();
    }

    public class TableCell extends JLabel implements TableCellRenderer {

        private Color colorL;
        private Color colorD;

        public TableCell(Color colorL, Color colorD) {
            this.colorL = colorL;
            this.colorD = colorD;
            setOpaque(true);
        }
        private LinkLabel label = new LinkLabel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            table.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    mouseEvent(evt);
                }
            });
            if (row == itsRow && column == itsColumn) {
                if (itsColumn == 2) {
                    if (table.getValueAt(itsRow, 2) != null) {
                        label.setText(table.getValueAt(itsRow, 2).toString());
                    } else {
                        label.setText(" ");
                    }
                }

                return label;
            } else {
                if (value != null) {
                    this.setText(value.toString());
                } else {
                    this.setText(" ");
                }
                if (row == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row == 1) {
                    this.setBackground(colorD);
                    return this;
                }
                if (row % 2 == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row % 2 != 0) {
                    this.setBackground(colorD);
                    return this;
                }
                return this;
            }
            //
        }

        // Xử lý click đúp lấy dữ liệu từ list sang form nhap
        public void mouseEvent(MouseEvent e) {
            if (isEdit == true) {
                return;
            }
            JTable aTable = (JTable) e.getSource();
            int selct = aTable.getSelectedRow();
            int sectcol = aTable.getSelectedColumn();
            if (selct == itsRow && sectcol == 2) {
                if (aTable.getValueAt(selct, sectcol) != null) {
                    Product p1 = (Product) aTable.getValueAt(selct, sectcol);
                    TopComponent tc1 = WindowManager.getDefault().findTopComponent("ProductViewerTopComponent");
                    if (tc1.isOpened()) {
                        tc1.close();
                    }
                    TopComponent tc = WindowManager.getDefault().findTopComponent("ProductCreatorTopComponent");
                    if (tc.isOpened() == false) {
                        tc.open();
                        tc.requestActive();
                    } else {
                        tc.requestActive();
                    }
                    getObject(p1.getProductId());
                }

            }
            aTable.clearSelection();
        }
    }

    private void getObject(String id) {
        Collection<? extends IGetObject> allObject = Lookup.getDefault().lookupAll(IGetObject.class);
        for (IGetObject getObject : allObject) {
            if (getObject instanceof IProductCreater || getObject instanceof IProductExtCreater) {
                getObject.getObject(id);
            }
        }
    }
}
