/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeToolbar.java
 *
 * Created on Feb 28, 2012, 3:24:58 PM
 */
package vn.com.hkt.basic.toolbar.gui.employee;

import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.basic.toolbar.api.ITabToolbar;
import vn.com.hkt.basic.toolbar.api.emloyee.IEmployeeToolbar;

/**
 *
 * @author BinLe
 */
@ServiceProvider(service=ITabToolbar.class)
public class EmployeeToolbar extends javax.swing.JPanel implements IEmployeeToolbar{

    /** Creates new form EmployeeToolbar */
    public EmployeeToolbar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/danhsachnhansu.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton4.text")); // NOI18N
        jButton4.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton4.actionCommand")); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/cocaunhansu.png"))); // NOI18N
        jButton5.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton5.text")); // NOI18N
        jButton5.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton5.actionCommand")); // NOI18N
        jButton5.setAlignmentY(0.0F);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/xephangtiemnang.png"))); // NOI18N
        jButton6.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton6.text")); // NOI18N
        jButton6.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton6.actionCommand")); // NOI18N
        jButton6.setAlignmentY(0.0F);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/xephangtongthe.png"))); // NOI18N
        jButton7.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton7.text")); // NOI18N
        jButton7.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton7.actionCommand")); // NOI18N
        jButton7.setAlignmentY(0.0F);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/xephangdoanhthu.png"))); // NOI18N
        jButton8.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton8.text")); // NOI18N
        jButton8.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton8.actionCommand")); // NOI18N
        jButton8.setAlignmentY(0.0F);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/xephangloinhuan.png"))); // NOI18N
        jButton9.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton9.text")); // NOI18N
        jButton9.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton9.actionCommand")); // NOI18N
        jButton9.setAlignmentY(0.0F);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jPanel2.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/nhiemvucanhan.png"))); // NOI18N
        jButton10.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton10.text")); // NOI18N
        jButton10.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton10.actionCommand")); // NOI18N
        jButton10.setAlignmentY(0.0F);
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/phanbocongviec.png"))); // NOI18N
        jButton11.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton11.text")); // NOI18N
        jButton11.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton11.actionCommand")); // NOI18N
        jButton11.setAlignmentY(0.0F);
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/nhiemvuhangngay.png"))); // NOI18N
        jButton12.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton12.text")); // NOI18N
        jButton12.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton12.actionCommand")); // NOI18N
        jButton12.setAlignmentY(0.0F);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/nhiemvutheoduan.png"))); // NOI18N
        jButton13.setText(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton13.text")); // NOI18N
        jButton13.setActionCommand(org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jButton13.actionCommand")); // NOI18N
        jButton13.setAlignmentY(0.0F);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(EmployeeToolbar.class, "EmployeeToolbar.jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabToolbarName() {
        return TAB_NAME;
    }

    @Override
    public int getTabToolbarIndex() {
        return TAB_INDEX;
    }
}
