/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DailyPanel.java
 *
 * Created on Feb 21, 2012, 9:26:01 AM
 */
package vn.com.hkt.pilot.calendaroption.ui.panel;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author khangpn
 */
public class DailyPanel extends javax.swing.JPanel{
    
    private SpinnerNumberModel numberModel;

    public JRadioButton getRdoEvery() {
        return rdoEvery;
    }

    public void setRdoEvery(JRadioButton rdoEvery) {
        this.rdoEvery = rdoEvery;
    }

    public JRadioButton getRdoEveryWeekday() {
        return rdoEveryWeekday;
    }

    public void setRdoEveryWeekday(JRadioButton rdoEveryWeekday) {
        this.rdoEveryWeekday = rdoEveryWeekday;
    }

    public JSpinner getSprEvery() {
        return sprEvery;
    }

    public void setSprEvery(JSpinner sprEvery) {
        this.sprEvery = sprEvery;
    }
    
    private ButtonGroup buttonGroup;
    private boolean choose = false;
    private int day = 0;
    
    /** Creates new form DailyPanel */
    public DailyPanel() {
        initComponents();
        loadSpinnerModel();
        sprEvery.setModel(numberModel);
        buttonGroup = new ButtonGroup();        
        buttonGroup.add(rdoEvery);
        buttonGroup.add(rdoEveryWeekday);      
    }
    
    protected void loadSpinnerModel(){
        numberModel = new SpinnerNumberModel(1, 1, 200, 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoEvery = new javax.swing.JRadioButton();
        sprEvery = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        rdoEveryWeekday = new javax.swing.JRadioButton();

        rdoEvery.setText(org.openide.util.NbBundle.getMessage(DailyPanel.class, "DailyPanel.rdoEvery.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DailyPanel.class, "DailyPanel.jLabel1.text")); // NOI18N

        rdoEveryWeekday.setText(org.openide.util.NbBundle.getMessage(DailyPanel.class, "DailyPanel.rdoEveryWeekday.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoEvery)
                        .addGap(18, 18, 18)
                        .addComponent(sprEvery, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(rdoEveryWeekday))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoEvery)
                    .addComponent(sprEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoEveryWeekday)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rdoEvery;
    private javax.swing.JRadioButton rdoEveryWeekday;
    private javax.swing.JSpinner sprEvery;
    // End of variables declaration//GEN-END:variables

}
