/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WeeklyPanel.java
 *
 * Created on Feb 21, 2012, 10:01:05 AM
 */
package vn.com.hkt.pilot.calendaroption.ui.panel;

import javax.swing.JCheckBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author khangpn
 */
public class WeeklyPanel extends javax.swing.JPanel {

    private SpinnerNumberModel spinnerNumberModel;
    
    /** Creates new form WeeklyPanel */
    public WeeklyPanel() {
        initComponents();
        loadSpinnerModel();
        sprWeeks.setModel(spinnerNumberModel);
    }
    
    protected void loadSpinnerModel(){
        spinnerNumberModel = new SpinnerNumberModel(1, 1, 200, 1);
    }

    public JCheckBox getCboFri() {
        return cboFri;
    }

    public void setCboFri(JCheckBox cboFri) {
        this.cboFri = cboFri;
    }

    public JCheckBox getCboMon() {
        return cboMon;
    }

    public void setCboMon(JCheckBox cboMon) {
        this.cboMon = cboMon;
    }

    public JCheckBox getCboSat() {
        return cboSat;
    }

    public void setCboSat(JCheckBox cboSat) {
        this.cboSat = cboSat;
    }

    public JCheckBox getCboSun() {
        return cboSun;
    }

    public void setCboSun(JCheckBox cboSun) {
        this.cboSun = cboSun;
    }

    public JCheckBox getCboThu() {
        return cboThu;
    }

    public void setCboThu(JCheckBox cboThu) {
        this.cboThu = cboThu;
    }

    public JCheckBox getCboTue() {
        return cboTue;
    }

    public void setCboTue(JCheckBox cboTue) {
        this.cboTue = cboTue;
    }

    public JCheckBox getCboWed() {
        return cboWed;
    }

    public void setCboWed(JCheckBox cboWed) {
        this.cboWed = cboWed;
    }

    public JSpinner getSprWeeks() {
        return sprWeeks;
    }

    public void setSprWeeks(JSpinner sprWeeks) {
        this.sprWeeks = sprWeeks;
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sprWeeks = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cboMon = new javax.swing.JCheckBox();
        cboWed = new javax.swing.JCheckBox();
        cboFri = new javax.swing.JCheckBox();
        cboSun = new javax.swing.JCheckBox();
        cboSat = new javax.swing.JCheckBox();
        cboThu = new javax.swing.JCheckBox();
        cboTue = new javax.swing.JCheckBox();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.jLabel2.text")); // NOI18N

        cboMon.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboMon.text")); // NOI18N
        cboMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonActionPerformed(evt);
            }
        });

        cboWed.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboWed.text")); // NOI18N

        cboFri.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboFri.text")); // NOI18N

        cboSun.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboSun.text")); // NOI18N

        cboSat.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboSat.text")); // NOI18N

        cboThu.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboThu.text")); // NOI18N

        cboTue.setText(org.openide.util.NbBundle.getMessage(WeeklyPanel.class, "WeeklyPanel.cboTue.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sprWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboMon)
                                .addGap(12, 12, 12)
                                .addComponent(cboTue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboFri)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboSat)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSun)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboWed)
                                .addGap(18, 18, 18)
                                .addComponent(cboThu)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboMon)
                        .addComponent(cboTue))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboWed)
                        .addComponent(cboThu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFri)
                    .addComponent(cboSun)
                    .addComponent(cboSat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void cboMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cboMonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cboFri;
    private javax.swing.JCheckBox cboMon;
    private javax.swing.JCheckBox cboSat;
    private javax.swing.JCheckBox cboSun;
    private javax.swing.JCheckBox cboThu;
    private javax.swing.JCheckBox cboTue;
    private javax.swing.JCheckBox cboWed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner sprWeeks;
    // End of variables declaration//GEN-END:variables
}
