/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * YearlyPanel.java
 *
 * Created on Feb 21, 2012, 10:21:46 AM
 */
package vn.com.hkt.pilot.calendaroption.ui.panel;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author khangpn
 */
public class YearlyPanel extends javax.swing.JPanel {

    private SpinnerNumberModel spinnerNumberModel;
    private ButtonGroup buttonGroup;

    /** Creates new form YearlyPanel */
    public YearlyPanel() {
        initComponents();

        loadSpinnerModel();
        sprDayOfMonth.setModel(spinnerNumberModel);

        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdoDay);
        buttonGroup.add(rdoLevel);
    }

    protected void loadSpinnerModel() {
        spinnerNumberModel = new SpinnerNumberModel(1, 1, 200, 1);
    }

    public ButtonGroup getButtonGroup() {
        return buttonGroup;
    }

    public void setButtonGroup(ButtonGroup buttonGroup) {
        this.buttonGroup = buttonGroup;
    }

    public JComboBox getCboDayLevel() {
        return cboDayLevel;
    }

    public void setCboDayLevel(JComboBox cboDayLevel) {
        this.cboDayLevel = cboDayLevel;
    }

    public JComboBox getCboDayOfWeek() {
        return cboDayOfWeek;
    }

    public void setCboDayOfWeek(JComboBox cboDayOfWeek) {
        this.cboDayOfWeek = cboDayOfWeek;
    }

    public JComboBox getCboMonth() {
        return cboMonth;
    }

    public void setCboMonth(JComboBox cboMonth) {
        this.cboMonth = cboMonth;
    }

    public JRadioButton getRdoDay() {
        return rdoDay;
    }

    public void setRdoDay(JRadioButton rdoDay) {
        this.rdoDay = rdoDay;
    }

    public JRadioButton getRdoLevel() {
        return rdoLevel;
    }

    public void setRdoLevel(JRadioButton rdoLevel) {
        this.rdoLevel = rdoLevel;
    }

    public JSpinner getSprDayOfMonth() {
        return sprDayOfMonth;
    }

    public void setSprDayOfMonth(JSpinner sprDayOfMonth) {
        this.sprDayOfMonth = sprDayOfMonth;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoDay = new javax.swing.JRadioButton();
        rdoLevel = new javax.swing.JRadioButton();
        sprDayOfMonth = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cboMonth = new javax.swing.JComboBox();
        cboDayLevel = new javax.swing.JComboBox();
        cboDayOfWeek = new javax.swing.JComboBox();

        rdoDay.setText(org.openide.util.NbBundle.getMessage(YearlyPanel.class, "YearlyPanel.rdoDay.text")); // NOI18N

        rdoLevel.setText(org.openide.util.NbBundle.getMessage(YearlyPanel.class, "YearlyPanel.rdoLevel.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(YearlyPanel.class, "YearlyPanel.jLabel1.text")); // NOI18N

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDayLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDayOfWeek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sprDayOfMonth))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoLevel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboDayLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboDayOfWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoDay)
                    .addComponent(sprDayOfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLevel)
                    .addComponent(cboDayLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDayOfWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboDayLevel;
    private javax.swing.JComboBox cboDayOfWeek;
    private javax.swing.JComboBox cboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rdoDay;
    private javax.swing.JRadioButton rdoLevel;
    private javax.swing.JSpinner sprDayOfMonth;
    // End of variables declaration//GEN-END:variables
}
