/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.account.manager.gui;

import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import vn.com.hkt.account.manager.gui.panel.AccountTypeInfomation;
import vn.com.hkt.account.manager.gui.panel.ListPersonAccount;
import vn.com.hkt.authenticate.manager.tools.AuthenticateManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.account.manager.gui//AccountManagerTotal//EN",
autostore = false)
@TopComponent.Description(preferredID = "AccountManagerTotalTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.account.manager.gui.AccountManagerTotalTopComponent")
@ActionReference(path = "Menu/Tài Khoản" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_AccountManagerTotalAction",
preferredID = "AccountManagerTotalTopComponent")
@Messages({
    "CTL_AccountManagerTotalAction=AccountManagerTotal",
    "CTL_AccountManagerTotalTopComponent=AccountManagerTotal Window",
    "HINT_AccountManagerTotalTopComponent=This is a AccountManagerTotal window"
})
public final class AccountManagerTotalTopComponent extends TopComponent {

    public AccountManagerTotalTopComponent() {
        initComponents();
        setName(Bundle.CTL_AccountManagerTotalTopComponent());
        setToolTipText(Bundle.HINT_AccountManagerTotalTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnListPersonAccount = new javax.swing.JButton();
        btnCreateAccountType = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(btnListPersonAccount, org.openide.util.NbBundle.getMessage(AccountManagerTotalTopComponent.class, "AccountManagerTotalTopComponent.btnListPersonAccount.text")); // NOI18N
        btnListPersonAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonAccountActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCreateAccountType, org.openide.util.NbBundle.getMessage(AccountManagerTotalTopComponent.class, "AccountManagerTotalTopComponent.btnCreateAccountType.text")); // NOI18N
        btnCreateAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountTypeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(AccountManagerTotalTopComponent.class, "AccountManagerTotalTopComponent.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton9, org.openide.util.NbBundle.getMessage(AccountManagerTotalTopComponent.class, "AccountManagerTotalTopComponent.jButton9.text")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnListPersonAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAccountType)
                .addGap(368, 368, 368)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton7)
                .addComponent(jButton9))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnListPersonAccount)
                .addComponent(btnCreateAccountType))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListPersonAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonAccountActionPerformed
        ListPersonAccount listPersonAccount= new ListPersonAccount();
        listPersonAccount.setVisible(true);
        listPersonAccount.setScrollPane(jScrollPane1);
        jScrollPane1.setViewportView(listPersonAccount);
    }//GEN-LAST:event_btnListPersonAccountActionPerformed

    private void btnCreateAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountTypeActionPerformed
        AccountTypeInfomation ati= new AccountTypeInfomation();
        ati.setVisible(true);
        ati.setScrollPane(jScrollPane1);
        jScrollPane1.setViewportView(ati);
    }//GEN-LAST:event_btnCreateAccountTypeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AuthenticateManager.getAuthenticateManager().logout();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(null, AuthenticateManager.getAuthenticateManager().checkLogined());
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccountType;
    private javax.swing.JButton btnListPersonAccount;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
