/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.resto.toolbar.gui;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.resto.toolbar.gui//MainMenu//EN",
autostore = false)
@TopComponent.Description(preferredID = "MainMenuTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.resto.toolbar.gui.MainMenuTopComponent")
@ActionReference(path = "Menu/Restaurant" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MainMenuAction",
preferredID = "MainMenuTopComponent")
public final class MainMenuTopComponent extends TopComponent {

    private JButton btnchoise = null;
    private List<JButton> buttons= new ArrayList<JButton>();
    private void resetColorButton(){
        for(int i=0;i<buttons.size();i++){            
            buttons.get(i).setBackground(new Color(207, 218, 230));
        }
    }

    private class MyMouseListener implements MouseListener {

        private JButton btn;        

        public MyMouseListener(JButton btn) {
            this.btn = btn;
            buttons.add(btn);
        }

        @Override
        public void mouseClicked(MouseEvent e) {
//            btn.setBackground(new Color(242, 144, 28));//da cam click
            // JOptionPane.showMessageDialog(null, btn.getBackground().toString()); 
        }

        @Override
        public void mousePressed(MouseEvent e) {
            resetColorButton();
            btn.setBackground(new Color(255, 128, 0));//ấn xuống
        }

        @Override
        public void mouseReleased(MouseEvent e) { 

            btn.setBackground(new Color(255, 128, 0));//nhả chuột
            btnchoise=btn;
            
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            if(!btn.equals(btnchoise)) btn.setBackground(new Color(192, 192, 192));// màu di chuột
         
        }

        @Override
        public void mouseExited(MouseEvent e) {
            if(!btn.equals(btnchoise))
            //btn.setBackground(new Color(207, 218, 230));// rời chuột màu ghi về khu vực
             btn.setBackground(new Color(208,215,255));
        }
        //   public void MouseMoved()
    }

    public MainMenuTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(MainMenuTopComponent.class, "CTL_MainMenuTopComponent"));
        setToolTipText(NbBundle.getMessage(MainMenuTopComponent.class, "HINT_MainMenuTopComponent"));
    
        loadButton_Khuvuc();
    }

    public void loadButton_Khuvuc() {
        button_khuvuc1.setContentAreaFilled(false);        
        button_khuvuc1.setOpaque(true);
        button_khuvuc1.addMouseListener(new MyMouseListener(button_khuvuc1));

        button_khuvuc2.setContentAreaFilled(false);
        button_khuvuc2.setOpaque(true);
        button_khuvuc2.addMouseListener(new MyMouseListener(button_khuvuc2));

        button_khuvuc3.setContentAreaFilled(false);
        button_khuvuc3.setOpaque(true);
        button_khuvuc3.addMouseListener(new MyMouseListener(button_khuvuc3));

        button_khuvuc4.setContentAreaFilled(false);
        button_khuvuc4.setOpaque(true);
        button_khuvuc4.addMouseListener(new MyMouseListener(button_khuvuc4));
        resetColorButton();
        
        button_khuvuc1.setBackground(new Color(255, 128, 0));//da cam click 
        btnchoise=button_khuvuc1;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton21 = new javax.swing.JButton();
        panel_Tong = new javax.swing.JPanel();
        panle_Button_MainMenu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        panle_khuvuc = new javax.swing.JPanel();
        panle_Button_MainMenuExit = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        panle_Node_khuvuc = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        button_khuvuc2 = new javax.swing.JButton();
        button_khuvuc3 = new javax.swing.JButton();
        button_khuvuc4 = new javax.swing.JButton();
        button_khuvuc1 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_C = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jButton21, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton21.text")); // NOI18N

        panel_Tong.setBackground(new java.awt.Color(103, 153, 255));
        panel_Tong.setPreferredSize(new java.awt.Dimension(1323, 562));

        panle_Button_MainMenu.setOpaque(false);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton2.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton1.text_1")); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton3.text_1")); // NOI18N
        jButton3.setContentAreaFilled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton4.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton6.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton5.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton7.text_1")); // NOI18N

        javax.swing.GroupLayout panle_Button_MainMenuLayout = new javax.swing.GroupLayout(panle_Button_MainMenu);
        panle_Button_MainMenu.setLayout(panle_Button_MainMenuLayout);
        panle_Button_MainMenuLayout.setHorizontalGroup(
            panle_Button_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panle_Button_MainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        panle_Button_MainMenuLayout.setVerticalGroup(
            panle_Button_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panle_Button_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panle_khuvuc.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panle_khuvucLayout = new javax.swing.GroupLayout(panle_khuvuc);
        panle_khuvuc.setLayout(panle_khuvucLayout);
        panle_khuvucLayout.setHorizontalGroup(
            panle_khuvucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        panle_khuvucLayout.setVerticalGroup(
            panle_khuvucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        panle_Button_MainMenuExit.setOpaque(false);

        org.openide.awt.Mnemonics.setLocalizedText(jButton9, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton9.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton8, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton8.text_1")); // NOI18N

        javax.swing.GroupLayout panle_Button_MainMenuExitLayout = new javax.swing.GroupLayout(panle_Button_MainMenuExit);
        panle_Button_MainMenuExit.setLayout(panle_Button_MainMenuExitLayout);
        panle_Button_MainMenuExitLayout.setHorizontalGroup(
            panle_Button_MainMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panle_Button_MainMenuExitLayout.createSequentialGroup()
                .addContainerGap(737, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );
        panle_Button_MainMenuExitLayout.setVerticalGroup(
            panle_Button_MainMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panle_Button_MainMenuExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panle_Button_MainMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8)))
        );

        panle_Node_khuvuc.setBackground(new java.awt.Color(208, 215, 255));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/resto/image/button_back.jpg"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton10, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton10.text_1")); // NOI18N

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/resto/image/button_next.jpg"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton11, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.jButton11.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_khuvuc2, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_khuvuc2.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_khuvuc3, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_khuvuc3.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_khuvuc4, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_khuvuc4.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_khuvuc1, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_khuvuc1.text_1")); // NOI18N

        javax.swing.GroupLayout panle_Node_khuvucLayout = new javax.swing.GroupLayout(panle_Node_khuvuc);
        panle_Node_khuvuc.setLayout(panle_Node_khuvucLayout);
        panle_Node_khuvucLayout.setHorizontalGroup(
            panle_Node_khuvucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panle_Node_khuvucLayout.createSequentialGroup()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(button_khuvuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panle_Node_khuvucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panle_Node_khuvucLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(button_khuvuc4))
                    .addComponent(button_khuvuc2)
                    .addGroup(panle_Node_khuvucLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(button_khuvuc3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panle_Node_khuvucLayout.setVerticalGroup(
            panle_Node_khuvucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_khuvuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button_khuvuc4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button_khuvuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button_khuvuc3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        button_0.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_0, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_0.text_1")); // NOI18N

        button_1.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_1, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_1.text_1")); // NOI18N

        button_2.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_2, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_2.text_1")); // NOI18N

        button_3.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_3, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_3.text_1")); // NOI18N

        button_4.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_4, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_4.text_1")); // NOI18N

        button_5.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_5, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_5.text_1")); // NOI18N

        button_6.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_6, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_6.text_1")); // NOI18N

        button_7.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_7, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_7.text_1")); // NOI18N

        button_8.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_8, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_8.text_1")); // NOI18N

        button_9.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_9, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_9.text_1")); // NOI18N

        button_C.setFont(new java.awt.Font("Tahoma", 1, 14));
        org.openide.awt.Mnemonics.setLocalizedText(button_C, org.openide.util.NbBundle.getMessage(MainMenuTopComponent.class, "MainMenuTopComponent.button_C.text_1")); // NOI18N

        javax.swing.GroupLayout panel_TongLayout = new javax.swing.GroupLayout(panel_Tong);
        panel_Tong.setLayout(panel_TongLayout);
        panel_TongLayout.setHorizontalGroup(
            panel_TongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panle_Button_MainMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_TongLayout.createSequentialGroup()
                .addComponent(panle_Button_MainMenuExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_TongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panle_khuvuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TongLayout.createSequentialGroup()
                .addGroup(panel_TongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_TongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panle_Node_khuvuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_TongLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(button_0, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_8, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_C, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_TongLayout.setVerticalGroup(
            panel_TongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TongLayout.createSequentialGroup()
                .addComponent(panle_Button_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panle_Node_khuvuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panel_TongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_TongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panle_khuvuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panle_Button_MainMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Tong, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Tong, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_C;
    private javax.swing.JButton button_khuvuc1;
    private javax.swing.JButton button_khuvuc2;
    private javax.swing.JButton button_khuvuc3;
    private javax.swing.JButton button_khuvuc4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel panel_Tong;
    private javax.swing.JPanel panle_Button_MainMenu;
    private javax.swing.JPanel panle_Button_MainMenuExit;
    private javax.swing.JPanel panle_Node_khuvuc;
    private javax.swing.JPanel panle_khuvuc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
