/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtentionSB23PanelPhuCap_Thuong.java
 *
 * Created on Feb 29, 2012, 8:59:51 AM
 */
package vn.com.hkt.pilot.sb23.ui.panel;

import java.awt.Color;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.sb23.Installer;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author DONGTAM
 */
public class ExtentionSB23PanelPhuCap_Thuong extends javax.swing.JPanel implements IUserInterface{

    /**
     * Creates new form ExtentionSB23PanelPhuCap_Thuong
     */
    private ExtentionSB23CellPhuCap_Thuong cellPhuCap_Thuong;

    public ExtentionSB23PanelPhuCap_Thuong() {
        initComponents();
        cellPhuCap_Thuong = new ExtentionSB23CellPhuCap_Thuong();
        tblBonus.getColumnModel().getColumn(1).setCellEditor(cellPhuCap_Thuong);
        tblBonus.getColumnModel().getColumn(3).setCellEditor(cellPhuCap_Thuong);
        tblBonus.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblBonus.getColumnModel().getColumn(0).setMaxWidth(100);
        tblBonus.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblBonus.getColumnModel().getColumn(2).setMaxWidth(100);
        tblBonus.setRowSelectionAllowed(true);
        tblBonus.setColumnSelectionAllowed(false);
        tblBonus.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tblBonus, new Color(220, 228, 231), null, new Color(235, 239, 242), null);
    }

    public void reset() {
        cellPhuCap_Thuong.reset();
        tblBonus.setValueAt("", 0, 1);
        tblBonus.setValueAt("", 0, 3);
        tblBonus.setValueAt("", 1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBonus = new javax.swing.JTable();

        tblBonus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BHXH", " ", "Theo doanh thu", " "},
                {"BHYT", " ", null, " "}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblBonus);
        tblBonus.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtentionSB23PanelPhuCap_Thuong.class, "ExtentionSB23PanelPhuCap_Thuong.tblBonus.columnModel.title0")); // NOI18N
        tblBonus.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtentionSB23PanelPhuCap_Thuong.class, "ExtentionSB23PanelPhuCap_Thuong.tblBonus.columnModel.title1")); // NOI18N
        tblBonus.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtentionSB23PanelPhuCap_Thuong.class, "ExtentionSB23PanelPhuCap_Thuong.tblBonus.columnModel.title2")); // NOI18N
        tblBonus.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtentionSB23PanelPhuCap_Thuong.class, "ExtentionSB23PanelPhuCap_Thuong.tblBonus.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBonus;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện thông tin phụ cấp trong hợp đồng";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
