/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductPanel.java
 *
 * Created on Nov 23, 2011, 4:15:46 PM
 */
package vn.com.hkt.bom.product.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import vn.com.hkt.basic.Installer;
import vn.com.hkt.erm.department.ui.DepartmentCell;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.entities.system.dao.SystemSotfwareDAO;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
public class ProductPanel extends javax.swing.JPanel implements IUserInterface {

    private byte[] dataImages;
    private ProductCell productCell;
    private ImageIcon imageChoise;
    private SystemSotfwareDAO sotfwareBN = new SystemSotfwareDAO();
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();

    public byte[] getDataImages() {
        return dataImages;
    }

    public JLabel getLabelImage() {
        return lbImage;
    }

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        productCell = new ProductCell();
        tableProduct.getColumnModel().getColumn(1).setCellEditor(productCell);
        tableProduct.getColumnModel().getColumn(1).setCellEditor(new DepartmentCell());
        tableProduct.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableProduct.getColumnModel().getColumn(0).setMaxWidth(100);
        tableProduct.setRowSelectionAllowed(true);
        tableProduct.setColumnSelectionAllowed(false);
        tableProduct.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableProduct, colorL, null, colorD, null);
        tableProduct.setForeground(color);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setBorder(null);
        tableProduct.setTableHeader(null);
        this.removeAll();
        this.setLayout(new BorderLayout());
        panelTable.removeAll();
        panelTable.setLayout(new GridLayout());
        panelTable.add(tableProduct);
        panelTP.setLayout(new GridLayout());
        panelTP.add(panlePhoto);
        panelTP.add(panelTable);
        this.add(panelTong, BorderLayout.CENTER);
        JLabel label = new JLabel("       Thông tin cơ bản");
        label.setFont((new Font(" ", Font.BOLD, 14)));
        label.setForeground(new Color(0, 51, 102));
        label.setPreferredSize(new Dimension(WIDTH, 30));
        // label.setHorizontalAlignment(50);
        this.add(label, BorderLayout.NORTH);
        this.setAutoscrolls(true);
    }

    public void reset() {
        productCell.reset();
        tableProduct.setValueAt("", 0, 1);
        tableProduct.setValueAt("", 1, 1);
        tableProduct.setValueAt("", 2, 1);
        tableProduct.setValueAt("", 3, 1);
        tableProduct.setValueAt("", 4, 1);
        tableProduct.setValueAt("", 5, 1);
        dataImages = null;
        showImage();
    }

    public JTable getTableProduct() {
        return tableProduct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTong = new javax.swing.JPanel();
        panelTP = new javax.swing.JPanel();
        panlePhoto = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();

        panelTong.setPreferredSize(new java.awt.Dimension(839, 157));

        panelTP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTP.setPreferredSize(new java.awt.Dimension(827, 161));

        panlePhoto.setPreferredSize(new java.awt.Dimension(298, 149));

        lbImage.setText(org.openide.util.NbBundle.getMessage(ProductPanel.class, "ProductPanel.lbImage.text")); // NOI18N
        lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panlePhotoLayout = new javax.swing.GroupLayout(panlePhoto);
        panlePhoto.setLayout(panlePhotoLayout);
        panlePhotoLayout.setHorizontalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panlePhotoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        panlePhotoLayout.setVerticalGroup(
            panlePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTable.setPreferredSize(new java.awt.Dimension(412, 149));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 153));

        tableProduct.setBackground(new java.awt.Color(242, 241, 240));
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tên sản phẩm", " "},
                {"Mã sản phẩm", " "},
                {"Công ty", " "},
                {"Bộ phận, dự án", " "},
                {"Người phụ trách", " "},
                {"Sản phẩm mẹ", " "}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProduct.setRowHeight(26);
        tableProduct.setSelectionBackground(new java.awt.Color(192, 210, 224));
        tableProduct.setShowHorizontalLines(false);
        tableProduct.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tableProduct);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTPLayout = new javax.swing.GroupLayout(panelTP);
        panelTP.setLayout(panelTPLayout);
        panelTPLayout.setHorizontalGroup(
            panelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTPLayout.createSequentialGroup()
                .addComponent(panlePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
        );
        panelTPLayout.setVerticalGroup(
            panelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTongLayout = new javax.swing.GroupLayout(panelTong);
        panelTong.setLayout(panelTongLayout);
        panelTongLayout.setHorizontalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTP, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE))
        );
        panelTongLayout.setVerticalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTongLayout.createSequentialGroup()
                .addComponent(panelTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImageMouseClicked
        if (evt.getClickCount() < 2 || !tableProduct.isEnabled()) {
            return;
        }
        FileDialog fd = new FileDialog(new JDialog(), "Chọn ảnh");
        fd.setVisible(true);
        String d = fd.getDirectory();
        String f = fd.getFile();
        if (d == null || f == null) {
            return;
        }
        String fileName = d + f;
        try {
            ImageIcon image = new ImageIcon(fileName);
            Image img = image.getImage();
            Image newimg = img.getScaledInstance(lbImage.getWidth(), lbImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
            imageChoise = new ImageIcon(newimg);            
        } catch (Exception e) {
            imageChoise = new ImageIcon();            
        }
        loadImage();
    }//GEN-LAST:event_lbImageMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JPanel panelTP;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTong;
    private javax.swing.JPanel panlePhoto;
    private javax.swing.JTable tableProduct;
    // End of variables declaration//GEN-END:variables

    private byte[] convertImage2Byte(Image image) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            int width = image.getWidth(null);
            int height = image.getHeight(null);
            BufferedImage bi = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = bi.createGraphics();
            g2d.drawImage(image, 0, 0, null);
            ImageIO.write(bi, "JPEG", baos);
        } catch (IOException ex) {
            //handle it here.... not implemented yet...
        }
        return baos.toByteArray();
    }

    private void loadImage() {
        dataImages = convertImage2Byte(imageChoise.getImage());
        showImage();
    }
    private Icon icon;

    public void showImage() {
        try {
            if (dataImages == null) {
                lbImage.setText("Anh");
                lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                icon = new ImageIcon();
                lbImage.setIcon(icon);
            } else {
                lbImage.setEnabled(true);
                lbImage.setText("");
                lbImage.setBorder(null);
                icon = new ImageIcon(dataImages);
                lbImage.setIcon(imageChoise);
            }
        } catch (Exception e) {
            lbImage.setText("Anh");
            lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lbImage.setIcon(icon);
        }

    }

    public void setDataImages(byte[] dataImages) {
        this.dataImages = dataImages;
        this.imageChoise= new ImageIcon(dataImages);
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String toString() {
        return "Thông tin cơ bản";
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện thông tin cơ bản của sản phẩm";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }
}
