/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.basic.toolbar.gui.data;

import java.awt.FlowLayout;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import org.jfree.layout.FormatLayout;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.basic.toolbar.api.ITabToolbar;
import vn.com.hkt.basic.toolbar.api.data.IDataToolbar;
import vn.com.hkt.basic.toolbar.api.data.ISubDataToolbar;

/**
 *
 * @author BinLe
 */
@ServiceProvider(service=ITabToolbar.class)
public class DataToolbar extends javax.swing.JPanel implements IDataToolbar {

    /**
     * Creates new form DataToolbar
     */
    public DataToolbar() {
        initComponents();
    }
    
    public void loadSubDataToolbar(){
        this.setLayout(new FlowLayout(5));
        List<ISubDataToolbar> listSubDataToolbar= (List<ISubDataToolbar>) Lookup.getDefault().lookupAll(ISubDataToolbar.class);
        for (int i=0;i<listSubDataToolbar.size();i++){
           this.add((JPanel)listSubDataToolbar.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/nghiepvumoi.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton1.text")); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/khachhangcanhan.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton2.text")); // NOI18N
        jButton2.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton2.actionCommand")); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/khachangdoanhnghiep.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton4.text")); // NOI18N
        jButton4.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton4.actionCommand")); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/giasanphamdichvu.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton3.text")); // NOI18N
        jButton3.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton3.actionCommand")); // NOI18N
        jButton3.setAlignmentY(0.0F);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/chuongtrinhkhuyenmai.png"))); // NOI18N
        jButton5.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton5.text")); // NOI18N
        jButton5.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton5.actionCommand")); // NOI18N
        jButton5.setAlignmentY(0.0F);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5)
                    .addComponent(jButton3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jPanel2.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/phongbanmoi.png"))); // NOI18N
        jButton6.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton6.text")); // NOI18N
        jButton6.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton6.actionCommand")); // NOI18N
        jButton6.setAlignmentY(0.0F);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/Nhansumoi.png"))); // NOI18N
        jButton7.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton7.text")); // NOI18N
        jButton7.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton7.actionCommand")); // NOI18N
        jButton7.setAlignmentY(0.0F);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/doanhnghiepmoi.png"))); // NOI18N
        jButton8.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton8.text")); // NOI18N
        jButton8.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton8.actionCommand")); // NOI18N
        jButton8.setAlignmentY(0.0F);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/sanphammoi.png"))); // NOI18N
        jButton9.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton9.text")); // NOI18N
        jButton9.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton9.actionCommand")); // NOI18N
        jButton9.setAlignmentY(0.0F);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM)); // NOI18N

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suanghiepvu.png"))); // NOI18N
        jButton10.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton10.text")); // NOI18N
        jButton10.setAlignmentY(0.0F);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suagia.png"))); // NOI18N
        jButton11.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton11.text")); // NOI18N
        jButton11.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton11.actionCommand")); // NOI18N
        jButton11.setAlignmentY(0.0F);
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suakhuyenmai.png"))); // NOI18N
        jButton12.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton12.text")); // NOI18N
        jButton12.setActionCommand(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton12.actionCommand")); // NOI18N
        jButton12.setAlignmentY(0.0F);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suaphongban.png"))); // NOI18N
        jButton13.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton13.text")); // NOI18N
        jButton13.setAlignmentY(0.0F);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suanhanvien.png"))); // NOI18N
        jButton14.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton14.text")); // NOI18N
        jButton14.setAlignmentY(0.0F);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suadoanhnghiep.png"))); // NOI18N
        jButton15.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton15.text")); // NOI18N
        jButton15.setAlignmentY(0.0F);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/basic/toolbar/icon/suasanpham.png"))); // NOI18N
        jButton16.setText(org.openide.util.NbBundle.getMessage(DataToolbar.class, "DataToolbar.jButton16.text")); // NOI18N
        jButton16.setAlignmentY(0.0F);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabToolbarName() {
        return TAB_NAME;
    }

    @Override
    public int getTabToolbarIndex() {
        return TAB_INDEX;
    }
    
}
