/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListSB51Panel.java
 *
 * Created on Feb 15, 2012, 1:38:30 PM
 */
package vn.com.hkt.pilot.sb51.panel;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.japura.gui.LinkLabel;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import vn.com.hkt.basic.api.IOperationBN;
import vn.com.hkt.basic.api.ISystemSotfwareBN;
import vn.com.hkt.basic.api.IWidthTableBN;
import vn.com.hkt.basic.toolbar.BasicToolbarManager;
import vn.com.hkt.pilot.enterprise.viewer.api.EditCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.IEnableButton;
import vn.com.hkt.pilot.enterprise.viewer.api.IGetObject;
import vn.com.hkt.pilot.enterprise.viewer.api.RemoveCookieOperation;
import vn.com.hkt.pilot.enterprise.viewer.api.ResetCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.SaveCookieList;
import vn.com.hkt.pilot.enterprise.viewer.api.ViewCookieList;
import vn.com.hkt.pilot.entities.Enterprise;
import vn.com.hkt.pilot.entities.Operation;
import vn.com.hkt.pilot.entities.system.SystemSoftware;
import vn.com.hkt.pilot.identity.presentation.api.IUserInterface;
import vn.com.hkt.pilot.operation.viewer.api.IOperationExtViewer;
import vn.com.hkt.pilot.report.api.IReportListGUI;
import vn.com.hkt.pilot.report.api.IReportManager;
import vn.com.hkt.pilot.sb51.Installer;
import vn.com.hkt.pilot.sb51.entity.OperationPayment;
import vn.com.hkt.pilot.sb51.spi.OperationPaymentBN;
import vn.com.hkt.pilot.toobar.api.IResetFontSize;
import vn.com.hkt.pilot.ui.colortable.StripedTableCellRenderer;

/**
 *
 * @author longnt
 */
@ServiceProvider(service = IOperationExtViewer.class)
public class ListSB51Panel extends javax.swing.JPanel implements IOperationExtViewer, IResetFontSize, IUserInterface, MouseMotionListener,
        IReportListGUI, ViewCookieList, EditCookieList, SaveCookieList, RemoveCookieOperation, ResetCookieList {

    private int size;
    private String font;
    private ISystemSotfwareBN sotfwareBN = Lookup.getDefault().lookup(ISystemSotfwareBN.class);
    private List<SystemSoftware> listS = new ArrayList<SystemSoftware>();
    private DefaultTableModel model;
    private DefaultTableModel modelEdit;
    private int itsRow = 0;
    private int itsColumn = 0;
    private boolean isEdit = false;

    /** Creates new form ListSB51Panel */
    public ListSB51Panel() {
        initComponents();
        listS = sotfwareBN.selectAll();
        if (listS.size() > 0) {
            Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
            Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
            tableSB51.setSelectionBackground(new Color(192, 210, 224));
            StripedTableCellRenderer.installInColumn(tableSB51, colorL, null, colorD, null);
        }
        tableSB51.addMouseMotionListener(this);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSB51 = new javax.swing.JTable();

        tableSB51.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên nghiệp vụ", "Tình trạng", "Hình thức thanh toán", "Loai hóa đơn", "Số hóa đơn", "Số tài khoản", "Số tải khoản đối ứng"
            }
        ));
        jScrollPane1.setViewportView(tableSB51);
        tableSB51.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title0")); // NOI18N
        tableSB51.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title1")); // NOI18N
        tableSB51.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title2")); // NOI18N
        tableSB51.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title3")); // NOI18N
        tableSB51.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title4")); // NOI18N
        tableSB51.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title5")); // NOI18N
        tableSB51.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title6")); // NOI18N
        tableSB51.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(ListSB51Panel.class, "ListSB51Panel.tableSB51.columnModel.title7")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSB51;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getOperationExtViewer() {
        return this;
    }

    @Override
    public String toString() {
        return "Thông tin thanh toán";
    }

    @Override
    public Lookup getOperationExtViewerLookup() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public double getLevelNumber() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    // Liên thông font cỡ chữ, màu
    @Override
    public void resetFont() {
        listS = sotfwareBN.selectAll();
        size = tableSB51.getFont().getSize();
        font = listS.get(0).getFont().getFontName();
        tableSB51.setFont(new Font(font, 0, size));
    }

    @Override
    public void resetColorRowTable() {
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        StripedTableCellRenderer.installInColumn(tableSB51, colorL, null, colorD, null);
        tableSB51.repaint();
    }

    @Override
    public void resetSize() {
        listS = sotfwareBN.selectAll();
        font = tableSB51.getFont().getFontName();
        size = listS.get(0).getSizeWord();
        tableSB51.setFont(new Font(font, 0, size));

    }

    @Override
    public void resetColorWord() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorWord().getRed(), listS.get(0).getColorWord().getGreen(), listS.get(0).getColorWord().getBlue());
        tableSB51.setForeground(color);
        tableSB51.repaint();
    }

    @Override
    public void resetColorTitle() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorTitle().getRed(), listS.get(0).getColorTitle().getGreen(), listS.get(0).getColorTitle().getBlue());
        tableSB51.getTableHeader().setForeground(color);
        tableSB51.repaint();
    }

    @Override
    public void resetColorMouse() {
        listS = sotfwareBN.selectAll();
        Color color = new Color(listS.get(0).getColorMouseClick().getRed(), listS.get(0).getColorMouseClick().getGreen(), listS.get(0).getColorMouseClick().getBlue());
        tableSB51.setSelectionBackground(color);
        tableSB51.repaint();
    }

    @Override
    public String getUserInterfaceName() {
        return getClass().getSimpleName();
    }

    @Override
    public String getUserInterfaceDescription() {
        return "Giao diện thông tin thanh toán nghiệp vụ";
    }

    @Override
    public String getModuleName() {
        return Installer.MODULE_NAME;
    }

//   @Override
//    public void filterTable(JTable table, DefaultTableModel tableModel) {
//        tableRowSorter = new TableRowSorter<TableModel>(tableModel);
//        table.setRowSorter(tableRowSorter);
//    }
//
//    @Override
//    public void filterTable(String stringKey, int column) {
//        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + stringKey, column));
//        tableRowSorter.setSortKeys(null);
//    }
    @Override
    public Hashtable getTableHeader() {
        Hashtable hashtable = new Hashtable();
        int n = tableSB51.getColumnCount();
        int i;
        for (i = 0; i < n; i++) {
            hashtable.put(i, tableSB51.getColumnName(i).toString());
        }

        return hashtable;
    }

    @Override
    public void ViewCookieList() {
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    protected void setupTable() {
        IWidthTableBN widthTableBN = Lookup.getDefault().lookup(IWidthTableBN.class);
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        tableSB51.setSelectionBackground(new Color(192, 210, 224));
        StripedTableCellRenderer.installInColumn(tableSB51, colorL, null, colorD, null);

        int sizeId = widthTableBN.getWidth1();
        //int sizeLogo = widthTableBN.getWidth2();
        int sizeName = widthTableBN.getWidth3();

        tableSB51.getColumnModel().getColumn(0).setMaxWidth(sizeId);
        tableSB51.getColumnModel().getColumn(0).setPreferredWidth(sizeId);

        tableSB51.getColumnModel().getColumn(1).setMaxWidth(sizeName);
        tableSB51.getColumnModel().getColumn(1).setPreferredWidth(sizeName);

        tableSB51.getColumnModel().getColumn(0).setResizable(false);
        tableSB51.getColumnModel().getColumn(1).setResizable(false);
        tableSB51.getColumnModel().getColumn(2).setResizable(false);
        tableSB51.getColumnModel().getColumn(3).setResizable(false);
        tableSB51.getColumnModel().getColumn(4).setResizable(false);
        tableSB51.getColumnModel().getColumn(5).setResizable(false);
        tableSB51.getColumnModel().getColumn(6).setResizable(false);
        tableSB51.getColumnModel().getColumn(7).setResizable(false);
        tableSB51.getTableHeader().setReorderingAllowed(false);
    }

    @Override
    public void remove() throws IOException {
        int i = tableSB51.getSelectedRow(); // chọn hàng để xóa
        if (i >= 0) {
            Enterprise bean = (Enterprise) tableSB51.getValueAt(i, 2); // Tìm kiếm Enterprise theo ID
            Collection<? extends RemoveCookieOperation> allRemoveCookie = Lookup.getDefault().lookupAll(RemoveCookieOperation.class);
            for (RemoveCookieOperation r : allRemoveCookie) {
                r.removeObject(bean.getId());
            }
        }
    }

    @Override
    public void removeObject(int id) throws IOException {
        OperationPaymentBN dao = new OperationPaymentBN();
        try {
            dao.delete(id);
        } catch (Exception e) {
        }
    }

    public void resetTable() {
        listS = sotfwareBN.selectAll();
        Color colorL = new Color(listS.get(0).getColorLight().getRed(), listS.get(0).getColorLight().getGreen(), listS.get(0).getColorLight().getBlue());
        Color colorD = new Color(listS.get(0).getColorDark().getRed(), listS.get(0).getColorDark().getGreen(), listS.get(0).getColorDark().getBlue());
        TableCell tableCell = new TableCell(colorL, colorD);
        tableSB51.getColumnModel().getColumn(1).setCellRenderer(tableCell);
        tableSB51.getColumnModel().getColumn(4).setCellRenderer(tableCell);
        tableSB51.getColumnModel().getColumn(5).setCellRenderer(tableCell);
        tableSB51.getColumnModel().getColumn(6).setCellRenderer(tableCell);
        tableSB51.setRowHeight(26);
    }

    public void resetTableEdit() {
        tableSB51.setRowHeight(26);
    }

    private DefaultTableModel getModel() {
        OperationPaymentBN dao = new OperationPaymentBN();
        IOperationBN operationBN = Lookup.getDefault().lookup(IOperationBN.class);
        Enterprise enterpriseChoise = null;
        String[] header = {"Mã", "Tên nghiệp vụ", "Tình trạng", "Hình thức thanh toán", "Loai hóa đơn", "Số hóa đơn", "Số tài khoản", "Số tải khoản đối ứng"};
        DefaultTableModel m = new DefaultTableModel(header, 0);
        List<OperationPayment> list = new ArrayList<OperationPayment>();
        enterpriseChoise = BasicToolbarManager.getBasicToolbar().getEnterprise();
        if (enterpriseChoise == null) {
            list = dao.selectAll();
        } else {
            list = dao.getByEnterpriser(enterpriseChoise);
        }
        for (OperationPayment bean : list) {
            try {
                int idOperation = bean.getOperationIdActual();
                Operation operation = operationBN.getById(idOperation);
                Object[] rows = {operation.getOperationId(), operation, " tinh trang", "HTTT", bean.getBillTypeIdActual(), bean.getBillCode(), bean.getAccount(), bean.getCorrespondingAccount()};
                m.addRow(rows);
            } catch (Exception ex) {
            }
        }

        return m;
    }

    public void loadData() {
        model = this.getModel();
        tableSB51.removeAll();
        tableSB51.setModel(model);
        resetTable();
        setupTable();
    }

    public void loadDataEdit() {
        modelEdit = this.getModel();
        tableSB51.removeAll();
        tableSB51.setModel(modelEdit);
        resetTableEdit();
        setupTable();
    }

    public void saveData() {
        //aaaaaaaaaaaaaaaaaaaaaaaaaa//aaaaaaaaaaaaaaaaaaaaaaaaaa
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        if (isEdit == false) {
            JTable aTable = (JTable) e.getSource();
            itsRow = aTable.rowAtPoint(e.getPoint());
            itsColumn = aTable.columnAtPoint(e.getPoint());
            aTable.repaint();
        }
    }

    @Override
    public void exportReport() {
        IReportManager reportManager = Lookup.getDefault().lookup(IReportManager.class);

        if (reportManager
                == null) {
            return;
        }
        String[] keys1 = {"prTenDoanhNghiep", "prDiaChi", "prTenBaoCao", "prNgayLap", "prNguoiLapBaoCao"};
        String[] values1 = {"HKT Consultant", "66 Trần Thái Tông Hà Nội", "", "16/03/2012", "Đồng Thị Tâm"};
        String keys2[] = new String[tableSB51.getColumnCount()];
        String values2[] = new String[tableSB51.getColumnCount()];
        for (int i = 0; i < tableSB51.getColumnCount(); i++) {
            keys2[i] = "prColumn_" + i;
            values2[i] = tableSB51.getColumnName(i).toString();
        }
        String[] keys = new String[keys1.length + keys2.length];
        String[] values = new String[values1.length + values2.length];
        System.arraycopy(keys1, 0, keys, 0, keys1.length);
        System.arraycopy(keys2, 0, keys, keys1.length, keys2.length);
        System.arraycopy(values1, 0, values, 0, values1.length);
        System.arraycopy(values2, 0, values, values1.length, values2.length);
        HashMap map = reportManager.getHashMap(keys, values);
        DefaultTableModel md = reportManager.getModel(tableSB51);
        reportManager.setReportManager(map, md);
        reportManager.exportReport();
    }

    @Override
    public void EditCookieList(boolean b) throws IOException {
        isEdit = b;
        if (isEdit == true) {
            loadDataEdit();
        } else {
            loadData();
        }
    }

    @Override
    public void SaveCookieList() throws IOException {
        saveData();
    }

    @Override
    public void resetCookie() throws IOException {
        ViewCookieList();
    }

    public class TableCell extends JLabel implements TableCellRenderer {

        private Color colorL;
        private Color colorD;

        public TableCell(Color colorL, Color colorD) {
            this.colorL = colorL;
            this.colorD = colorD;
            setOpaque(true);
        }
        private LinkLabel label = new LinkLabel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            table.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    mouseEvent(evt);
                }
            });
            if (row == itsRow && column == itsColumn) {
                if (itsColumn == 2) {
                    label.setText(table.getValueAt(itsRow, 1).toString());
                }


                return label;
            } else {
                if (value != null) {
                    this.setText(value.toString());
                } else {
                    this.setText(" ");
                }
                if (row == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row == 1) {
                    this.setBackground(colorD);
                    return this;
                }
                if (row % 2 == 0) {
                    this.setBackground(colorL);
                    return this;
                }
                if (row % 2 != 0) {
                    this.setBackground(colorD);
                    return this;
                }
                return this;
            }
            //
        }
        // Xử lý click đúp lấy dữ liệu từ list sang form nhap

        public void mouseEvent(MouseEvent e) {
            //if(e.getClickCount()<2) return;
            if (isEdit == true) {
                return;
            }
            JTable aTable = (JTable) e.getSource();
            int selct = aTable.getSelectedRow();
            int sectcol = aTable.getSelectedColumn();
            if (selct == itsRow && sectcol == 2) {
                if (aTable.getValueAt(selct, sectcol) != null) {
                    try {
                        // Lam sau
                        //Enterprise e1 = (Enterprise) aTable.getValueAt(selct, sectcol);
                        //openCreatorcomponent("EnterpriseViewerTopComponent", "EnterpriseCreatorTopComponent");
                        //getObject(e1.getEnterpriseId());
                    } catch (Exception ex) {
                        return;
                    }
                }

            }
            aTable.clearSelection();
        }
    }

    public void openCreatorcomponent(String s1, String s2) {
        TopComponent tc1 = WindowManager.getDefault().findTopComponent(s1);
        if (tc1.isOpened()) {
            tc1.close();
        }
        TopComponent tc = WindowManager.getDefault().findTopComponent(s2);
        if (tc.isOpened() == false) {
            tc.open();
            tc.requestActive();
        } else {
            tc.requestActive();
        }
    }

    // Lấy liên thông Enterprise
    private void getObject(String id) {
        setEnableButton();
        Collection<? extends IGetObject> allSave = Lookup.getDefault().lookupAll(IGetObject.class);
        for (IGetObject getObject : allSave) {
            getObject.getObject(id);
        }
    }

    private void setEnableButton() {
        Collection<? extends IEnableButton> all = Lookup.getDefault().lookupAll(IEnableButton.class);
        for (IEnableButton e : all) {
            try {
                e.enableButton();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }
}
